-- ============================================================================
-- 91_validate_core_deployment.sql - Post-deploy validation of the core DB
-- ============================================================================
-- Run against the CORE database of the newly deployed instance (SSMS).
-- SELECT-only. Expected values are taken from UAT on 2026-07-06 (the source
-- of the v1.0 baseline) with the two day-one rulings applied:
--   * 425 visualisation queries (9 MargeBrut* demo cards excluded)
--   * 5 integrations (TBTBookingMetrics001 on hold)
-- Every row should show PASS.
-- ============================================================================

WITH checks AS (
    SELECT 1 AS ord, 'core schema tables' AS chk, 15 AS expected,
           (SELECT COUNT(*) FROM sys.tables t JOIN sys.schemas s ON s.schema_id = t.schema_id WHERE s.name = 'core') AS actual
    UNION ALL
    SELECT 2, 'core programmable objects (SP+FN+TVF+TR)', 43,
           (SELECT COUNT(*) FROM sys.objects o JOIN sys.schemas s ON s.schema_id = o.schema_id
            WHERE s.name = 'core' AND o.type IN ('P','FN','IF','TF','TR') AND o.is_ms_shipped = 0)
    UNION ALL
    SELECT 3, 'DataVaultEntities rows', 146, (SELECT COUNT(*) FROM [core].[DataVaultEntities])
    UNION ALL
    SELECT 4, 'DeploymentObjects rows', 60, (SELECT COUNT(*) FROM [core].[DeploymentObjects])
    UNION ALL
    SELECT 5, 'PresentationControl rows', 42, (SELECT COUNT(*) FROM [core].[PresentationControl])
    UNION ALL
    SELECT 6, 'PresentationTables rows', 44, (SELECT COUNT(*) FROM [core].[PresentationTables])
    UNION ALL
    SELECT 7, 'VisualisationQueries rows', 425, (SELECT COUNT(*) FROM [core].[VisualisationQueries])
    UNION ALL
    SELECT 8, 'MargeBrut* queries (must be excluded)', 0,
           (SELECT COUNT(*) FROM [core].[VisualisationQueries] WHERE DataSetName LIKE 'MargeBrut%')
    UNION ALL
    SELECT 9, 'Active integrations (TBT on hold)', 5,
           (SELECT COUNT(*) FROM [core].[Integrations] WHERE IsActive = 1)
    UNION ALL
    SELECT 10, 'TBTBookingMetrics001 present (held)', 0,
           (SELECT COUNT(*) FROM [core].[Integrations] WHERE IntegrationName = 'TBTBookingMetrics001')
    -- per-integration STAGE_DDL parameter counts (DL table DDLs)
    UNION ALL SELECT 11, 'NCRAloha001 STAGE_DDL params', 21,
           (SELECT COUNT(*) FROM [int_ncraloha001].[GlobalParameters] WHERE Category = 'STAGE_DDL' AND IsActive = 1)
    UNION ALL SELECT 12, 'Marketman001 STAGE_DDL params', 34,
           (SELECT COUNT(*) FROM [int_marketman001].[GlobalParameters] WHERE Category = 'STAGE_DDL' AND IsActive = 1)
    UNION ALL SELECT 13, 'Growyze001 STAGE_DDL params', 13,
           (SELECT COUNT(*) FROM [int_growyze001].[GlobalParameters] WHERE Category = 'STAGE_DDL' AND IsActive = 1)
    UNION ALL SELECT 14, 'SurveyHero001 STAGE_DDL params', 41,
           (SELECT COUNT(*) FROM [int_surveyhero001].[GlobalParameters] WHERE Category = 'STAGE_DDL' AND IsActive = 1)
    UNION ALL SELECT 15, 'TROaP001 STAGE_DDL params', 48,
           (SELECT COUNT(*) FROM [int_troap001].[GlobalParameters] WHERE Category = 'STAGE_DDL' AND IsActive = 1)
    -- per-integration StagingControl: Staging steps
    UNION ALL SELECT 16, 'NCRAloha001 Staging steps', 27,
           (SELECT COUNT(*) FROM [int_ncraloha001].[StagingControl] WHERE step_type = 'Staging')
    UNION ALL SELECT 17, 'Marketman001 Staging steps', 20,
           (SELECT COUNT(*) FROM [int_marketman001].[StagingControl] WHERE step_type = 'Staging')
    UNION ALL SELECT 18, 'Growyze001 Staging steps', 16,
           (SELECT COUNT(*) FROM [int_growyze001].[StagingControl] WHERE step_type = 'Staging')
    UNION ALL SELECT 19, 'SurveyHero001 Staging steps', 3,
           (SELECT COUNT(*) FROM [int_surveyhero001].[StagingControl] WHERE step_type = 'Staging')
    UNION ALL SELECT 20, 'TROaP001 Staging steps', 22,
           (SELECT COUNT(*) FROM [int_troap001].[StagingControl] WHERE step_type = 'Staging')
    -- per-integration StagingControl: Load steps (generated by UploadEntityMappings in _Final)
    UNION ALL SELECT 21, 'NCRAloha001 Load steps', 34,
           (SELECT COUNT(*) FROM [int_ncraloha001].[StagingControl] WHERE step_type = 'Load')
    UNION ALL SELECT 22, 'Marketman001 Load steps', 24,
           (SELECT COUNT(*) FROM [int_marketman001].[StagingControl] WHERE step_type = 'Load')
    UNION ALL SELECT 23, 'Growyze001 Load steps', 23,
           (SELECT COUNT(*) FROM [int_growyze001].[StagingControl] WHERE step_type = 'Load')
    UNION ALL SELECT 24, 'SurveyHero001 Load steps', 4,
           (SELECT COUNT(*) FROM [int_surveyhero001].[StagingControl] WHERE step_type = 'Load')
    UNION ALL SELECT 25, 'TROaP001 Load steps', 22,
           (SELECT COUNT(*) FROM [int_troap001].[StagingControl] WHERE step_type = 'Load')
    -- per-integration EntityMappings
    UNION ALL SELECT 26, 'NCRAloha001 entity mappings', 34, (SELECT COUNT(*) FROM [int_ncraloha001].[EntityMappings])
    UNION ALL SELECT 27, 'Marketman001 entity mappings', 24, (SELECT COUNT(*) FROM [int_marketman001].[EntityMappings])
    UNION ALL SELECT 28, 'Growyze001 entity mappings', 23, (SELECT COUNT(*) FROM [int_growyze001].[EntityMappings])
    UNION ALL SELECT 29, 'SurveyHero001 entity mappings', 4, (SELECT COUNT(*) FROM [int_surveyhero001].[EntityMappings])
    UNION ALL SELECT 30, 'TROaP001 entity mappings', 22, (SELECT COUNT(*) FROM [int_troap001].[EntityMappings])
)
SELECT ord, chk, expected, actual,
       CASE WHEN expected = actual THEN 'PASS' ELSE 'FAIL' END AS result
FROM checks
ORDER BY ord;
