-- =========================================
-- Demo Data Loader for "The Oak & Vine"
-- Generated by demo-data Python generator
-- =========================================
-- Instructions:
--   1. Set @CsvPath to the full path of the output\ folder
--   2. Set @DatabaseName to the target organisation database name
--   3. Run the script from the core database context
--   4. After successful load, run the post-load commands printed at the end
-- =========================================
SET NOCOUNT ON;

DECLARE @CsvPath     NVARCHAR(500) = N'C:\threerocks_data\XMS BI\Release\ClaudeDevelopment\demo-data\output';
DECLARE @DatabaseName NVARCHAR(255) = N'20260316_XMS_{GUID}';
DECLARE @sql         NVARCHAR(MAX);

-- Uncomment to TRUNCATE all DV tables before a clean reload:
-- SET @sql = N'USE [' + @DatabaseName + N']
-- TRUNCATE TABLE [datavault].[SAT_LNK_INVITEM_LOCATION_OCCASION_PRODUCT]
-- TRUNCATE TABLE [datavault].[SAT_LNK_LOCATION_OCCASION_PRODUCT]
-- TRUNCATE TABLE [datavault].[SAT_LNK_INVITEM_OCCASION_PRODUCT]
-- TRUNCATE TABLE [datavault].[SAT_LNK_INVITEM_INVITEM]
-- TRUNCATE TABLE [datavault].[SAT_LNK_LINEITEM_LINEITEM]
-- TRUNCATE TABLE [datavault].[LNK_INVITEM_LOCATION_OCCASION_PRODUCT]
-- TRUNCATE TABLE [datavault].[LNK_LOCATION_OCCASION_PRODUCT]
-- TRUNCATE TABLE [datavault].[LNK_INVITEM_OCCASION_PRODUCT]
-- TRUNCATE TABLE [datavault].[LNK_INVITEM_INVITEM]
-- TRUNCATE TABLE [datavault].[LNK_LINEITEM_LINEITEM]
-- TRUNCATE TABLE [datavault].[LNK_INVREPORT_LOCATION]
-- TRUNCATE TABLE [datavault].[LNK_INVITEM_INVREPORT]
-- TRUNCATE TABLE [datavault].[LNK_LOCATION_STOCKEVENT]
-- TRUNCATE TABLE [datavault].[LNK_INVITEM_STOCKEVENT]
-- TRUNCATE TABLE [datavault].[LNK_DISCOUNT_LINEITEM]
-- TRUNCATE TABLE [datavault].[LNK_EMPLOYEE_LINEITEM]
-- TRUNCATE TABLE [datavault].[LNK_LINEITEM_OCCASION]
-- TRUNCATE TABLE [datavault].[LNK_LINEITEM_TAX]
-- TRUNCATE TABLE [datavault].[LNK_LINEITEM_PRODUCT]
-- TRUNCATE TABLE [datavault].[LNK_CUSTORDER_REVCENTER]
-- TRUNCATE TABLE [datavault].[LNK_CUSTORDER_OCCASION]
-- TRUNCATE TABLE [datavault].[LNK_CUSTORDER_LINEITEM]
-- TRUNCATE TABLE [datavault].[LNK_CUSTORDER_EMPLOYEE]
-- TRUNCATE TABLE [datavault].[LNK_CUSTORDER_LOCATION]
-- TRUNCATE TABLE [datavault].[SAT_INVREPORT]
-- TRUNCATE TABLE [datavault].[SAT_STOCKEVENT]
-- TRUNCATE TABLE [datavault].[SAT_LINEITEM]
-- TRUNCATE TABLE [datavault].[SAT_CUSTORDER]
-- TRUNCATE TABLE [datavault].[SAT_EMPLOYEE]
-- TRUNCATE TABLE [datavault].[SAT_DISCOUNT]
-- TRUNCATE TABLE [datavault].[SAT_REVCENTER]
-- TRUNCATE TABLE [datavault].[SAT_TAX]
-- TRUNCATE TABLE [datavault].[SAT_TENDER]
-- TRUNCATE TABLE [datavault].[SAT_OCCASION]
-- TRUNCATE TABLE [datavault].[SAT_SUPPLIER]
-- TRUNCATE TABLE [datavault].[SAT_INVITEM]
-- TRUNCATE TABLE [datavault].[SAT_PRODUCT]
-- TRUNCATE TABLE [datavault].[SAT_LOCATION]
-- TRUNCATE TABLE [datavault].[HUB_INVREPORT]
-- TRUNCATE TABLE [datavault].[HUB_STOCKEVENT]
-- TRUNCATE TABLE [datavault].[HUB_LINEITEM]
-- TRUNCATE TABLE [datavault].[HUB_CUSTORDER]
-- TRUNCATE TABLE [datavault].[HUB_DISCOUNT]
-- TRUNCATE TABLE [datavault].[HUB_REVCENTER]
-- TRUNCATE TABLE [datavault].[HUB_TAX]
-- TRUNCATE TABLE [datavault].[HUB_TENDER]
-- TRUNCATE TABLE [datavault].[HUB_OCCASION]
-- TRUNCATE TABLE [datavault].[HUB_EMPLOYEE]
-- TRUNCATE TABLE [datavault].[HUB_SUPPLIER]
-- TRUNCATE TABLE [datavault].[HUB_INVITEM]
-- TRUNCATE TABLE [datavault].[HUB_PRODUCT]
-- TRUNCATE TABLE [datavault].[HUB_LOCATION]
-- ';
-- EXEC sp_executesql @sql;

PRINT '========================================='
PRINT 'Demo Data Loader - The Oak & Vine'
PRINT '========================================='

-- =========================================
-- Phase 0: GlobalParameters
-- =========================================
PRINT ''
PRINT '--- Phase 0: GlobalParameters ---'
SET @sql = N'
MERGE INTO [' + @DatabaseName + N'].[core].[GlobalParameters] AS tgt
USING (VALUES
    (N''LINEITEM_START'',    N''2025-10-01'', N''DATE_RANGE''),
    (N''LINEITEM_END'',      N''2026-03-31'', N''DATE_RANGE''),
    (N''STOCKEVENT_START'',  N''2025-10-01'', N''DATE_RANGE''),
    (N''STOCKEVENT_END'',    N''2026-03-31'', N''DATE_RANGE'')
) AS src (ParameterName, ParameterValue, Category)
ON tgt.ParameterName = src.ParameterName
WHEN MATCHED THEN
    UPDATE SET ParameterValue = src.ParameterValue
WHEN NOT MATCHED THEN
    INSERT (ParameterName, ParameterValue, Category)
    VALUES (src.ParameterName, src.ParameterValue, src.Category);
';
EXEC sp_executesql @sql;
PRINT '  GlobalParameters set'

GO

-- =========================================
-- Phase 1: Hubs
-- =========================================
PRINT ''
PRINT '--- Phase 1: Hubs ---'

DECLARE @CsvPath     NVARCHAR(500) = N'C:\threerocks_data\XMS BI\Release\ClaudeDevelopment\demo-data\output';
DECLARE @DatabaseName NVARCHAR(255) = N'20260316_XMS_{GUID}';
DECLARE @sql         NVARCHAR(MAX);

-- === HUB_LOCATION ===
PRINT 'Loading HUB_LOCATION...'
BEGIN TRY
    CREATE TABLE #stg_hub_loc (
        HUB_ID   NVARCHAR(64),
        SRC      NVARCHAR(255),
        IS_DELETED NVARCHAR(5),
        LOAD_TS  NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_hub_loc FROM ''' + @CsvPath + N'\hub_location.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[HUB_LOCATION] (HUB_ID, SRC, IS_DELETED, LOAD_TS)
                 SELECT CONVERT(BINARY(32), HUB_ID, 2), SRC, CAST(IS_DELETED AS BIT), CAST(LOAD_TS AS DATETIME2)
                 FROM #stg_hub_loc';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_hub_loc;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_hub_loc') IS NOT NULL DROP TABLE #stg_hub_loc;
    RETURN;
END CATCH

-- === HUB_PRODUCT ===
PRINT 'Loading HUB_PRODUCT...'
BEGIN TRY
    CREATE TABLE #stg_hub_prod (
        HUB_ID   NVARCHAR(64),
        SRC      NVARCHAR(255),
        IS_DELETED NVARCHAR(5),
        LOAD_TS  NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_hub_prod FROM ''' + @CsvPath + N'\hub_product.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[HUB_PRODUCT] (HUB_ID, SRC, IS_DELETED, LOAD_TS)
                 SELECT CONVERT(BINARY(32), HUB_ID, 2), SRC, CAST(IS_DELETED AS BIT), CAST(LOAD_TS AS DATETIME2)
                 FROM #stg_hub_prod';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_hub_prod;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_hub_prod') IS NOT NULL DROP TABLE #stg_hub_prod;
    RETURN;
END CATCH

-- === HUB_INVITEM ===
PRINT 'Loading HUB_INVITEM...'
BEGIN TRY
    CREATE TABLE #stg_hub_inv (
        HUB_ID   NVARCHAR(64),
        SRC      NVARCHAR(255),
        IS_DELETED NVARCHAR(5),
        LOAD_TS  NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_hub_inv FROM ''' + @CsvPath + N'\hub_invitem.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[HUB_INVITEM] (HUB_ID, SRC, IS_DELETED, LOAD_TS)
                 SELECT CONVERT(BINARY(32), HUB_ID, 2), SRC, CAST(IS_DELETED AS BIT), CAST(LOAD_TS AS DATETIME2)
                 FROM #stg_hub_inv';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_hub_inv;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_hub_inv') IS NOT NULL DROP TABLE #stg_hub_inv;
    RETURN;
END CATCH

-- === HUB_SUPPLIER ===
PRINT 'Loading HUB_SUPPLIER...'
BEGIN TRY
    CREATE TABLE #stg_hub_sup (
        HUB_ID   NVARCHAR(64),
        SRC      NVARCHAR(255),
        IS_DELETED NVARCHAR(5),
        LOAD_TS  NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_hub_sup FROM ''' + @CsvPath + N'\hub_supplier.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[HUB_SUPPLIER] (HUB_ID, SRC, IS_DELETED, LOAD_TS)
                 SELECT CONVERT(BINARY(32), HUB_ID, 2), SRC, CAST(IS_DELETED AS BIT), CAST(LOAD_TS AS DATETIME2)
                 FROM #stg_hub_sup';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_hub_sup;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_hub_sup') IS NOT NULL DROP TABLE #stg_hub_sup;
    RETURN;
END CATCH

-- === HUB_EMPLOYEE ===
PRINT 'Loading HUB_EMPLOYEE...'
BEGIN TRY
    CREATE TABLE #stg_hub_emp (
        HUB_ID   NVARCHAR(64),
        SRC      NVARCHAR(255),
        IS_DELETED NVARCHAR(5),
        LOAD_TS  NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_hub_emp FROM ''' + @CsvPath + N'\hub_employee.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[HUB_EMPLOYEE] (HUB_ID, SRC, IS_DELETED, LOAD_TS)
                 SELECT CONVERT(BINARY(32), HUB_ID, 2), SRC, CAST(IS_DELETED AS BIT), CAST(LOAD_TS AS DATETIME2)
                 FROM #stg_hub_emp';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_hub_emp;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_hub_emp') IS NOT NULL DROP TABLE #stg_hub_emp;
    RETURN;
END CATCH

-- === HUB_OCCASION ===
PRINT 'Loading HUB_OCCASION...'
BEGIN TRY
    CREATE TABLE #stg_hub_occ (
        HUB_ID   NVARCHAR(64),
        SRC      NVARCHAR(255),
        IS_DELETED NVARCHAR(5),
        LOAD_TS  NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_hub_occ FROM ''' + @CsvPath + N'\hub_occasion.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[HUB_OCCASION] (HUB_ID, SRC, IS_DELETED, LOAD_TS)
                 SELECT CONVERT(BINARY(32), HUB_ID, 2), SRC, CAST(IS_DELETED AS BIT), CAST(LOAD_TS AS DATETIME2)
                 FROM #stg_hub_occ';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_hub_occ;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_hub_occ') IS NOT NULL DROP TABLE #stg_hub_occ;
    RETURN;
END CATCH

-- === HUB_TENDER ===
PRINT 'Loading HUB_TENDER...'
BEGIN TRY
    CREATE TABLE #stg_hub_tnd (
        HUB_ID   NVARCHAR(64),
        SRC      NVARCHAR(255),
        IS_DELETED NVARCHAR(5),
        LOAD_TS  NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_hub_tnd FROM ''' + @CsvPath + N'\hub_tender.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[HUB_TENDER] (HUB_ID, SRC, IS_DELETED, LOAD_TS)
                 SELECT CONVERT(BINARY(32), HUB_ID, 2), SRC, CAST(IS_DELETED AS BIT), CAST(LOAD_TS AS DATETIME2)
                 FROM #stg_hub_tnd';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_hub_tnd;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_hub_tnd') IS NOT NULL DROP TABLE #stg_hub_tnd;
    RETURN;
END CATCH

-- === HUB_TAX ===
PRINT 'Loading HUB_TAX...'
BEGIN TRY
    CREATE TABLE #stg_hub_tax (
        HUB_ID   NVARCHAR(64),
        SRC      NVARCHAR(255),
        IS_DELETED NVARCHAR(5),
        LOAD_TS  NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_hub_tax FROM ''' + @CsvPath + N'\hub_tax.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[HUB_TAX] (HUB_ID, SRC, IS_DELETED, LOAD_TS)
                 SELECT CONVERT(BINARY(32), HUB_ID, 2), SRC, CAST(IS_DELETED AS BIT), CAST(LOAD_TS AS DATETIME2)
                 FROM #stg_hub_tax';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_hub_tax;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_hub_tax') IS NOT NULL DROP TABLE #stg_hub_tax;
    RETURN;
END CATCH

-- === HUB_REVCENTER ===
PRINT 'Loading HUB_REVCENTER...'
BEGIN TRY
    CREATE TABLE #stg_hub_rev (
        HUB_ID   NVARCHAR(64),
        SRC      NVARCHAR(255),
        IS_DELETED NVARCHAR(5),
        LOAD_TS  NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_hub_rev FROM ''' + @CsvPath + N'\hub_revcenter.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[HUB_REVCENTER] (HUB_ID, SRC, IS_DELETED, LOAD_TS)
                 SELECT CONVERT(BINARY(32), HUB_ID, 2), SRC, CAST(IS_DELETED AS BIT), CAST(LOAD_TS AS DATETIME2)
                 FROM #stg_hub_rev';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_hub_rev;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_hub_rev') IS NOT NULL DROP TABLE #stg_hub_rev;
    RETURN;
END CATCH

-- === HUB_DISCOUNT ===
PRINT 'Loading HUB_DISCOUNT...'
BEGIN TRY
    CREATE TABLE #stg_hub_dis (
        HUB_ID   NVARCHAR(64),
        SRC      NVARCHAR(255),
        IS_DELETED NVARCHAR(5),
        LOAD_TS  NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_hub_dis FROM ''' + @CsvPath + N'\hub_discount.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[HUB_DISCOUNT] (HUB_ID, SRC, IS_DELETED, LOAD_TS)
                 SELECT CONVERT(BINARY(32), HUB_ID, 2), SRC, CAST(IS_DELETED AS BIT), CAST(LOAD_TS AS DATETIME2)
                 FROM #stg_hub_dis';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_hub_dis;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_hub_dis') IS NOT NULL DROP TABLE #stg_hub_dis;
    RETURN;
END CATCH

-- === HUB_CUSTORDER ===
PRINT 'Loading HUB_CUSTORDER...'
BEGIN TRY
    CREATE TABLE #stg_hub_co (
        HUB_ID   NVARCHAR(64),
        SRC      NVARCHAR(255),
        IS_DELETED NVARCHAR(5),
        LOAD_TS  NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_hub_co FROM ''' + @CsvPath + N'\hub_custorder.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[HUB_CUSTORDER] (HUB_ID, SRC, IS_DELETED, LOAD_TS)
                 SELECT CONVERT(BINARY(32), HUB_ID, 2), SRC, CAST(IS_DELETED AS BIT), CAST(LOAD_TS AS DATETIME2)
                 FROM #stg_hub_co';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_hub_co;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_hub_co') IS NOT NULL DROP TABLE #stg_hub_co;
    RETURN;
END CATCH

-- === HUB_LINEITEM ===
PRINT 'Loading HUB_LINEITEM...'
BEGIN TRY
    CREATE TABLE #stg_hub_li (
        HUB_ID   NVARCHAR(64),
        SRC      NVARCHAR(255),
        IS_DELETED NVARCHAR(5),
        LOAD_TS  NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_hub_li FROM ''' + @CsvPath + N'\hub_lineitem.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[HUB_LINEITEM] (HUB_ID, SRC, IS_DELETED, LOAD_TS)
                 SELECT CONVERT(BINARY(32), HUB_ID, 2), SRC, CAST(IS_DELETED AS BIT), CAST(LOAD_TS AS DATETIME2)
                 FROM #stg_hub_li';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_hub_li;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_hub_li') IS NOT NULL DROP TABLE #stg_hub_li;
    RETURN;
END CATCH

-- === HUB_STOCKEVENT ===
PRINT 'Loading HUB_STOCKEVENT...'
BEGIN TRY
    CREATE TABLE #stg_hub_se (
        HUB_ID   NVARCHAR(64),
        SRC      NVARCHAR(255),
        IS_DELETED NVARCHAR(5),
        LOAD_TS  NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_hub_se FROM ''' + @CsvPath + N'\hub_stockevent.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[HUB_STOCKEVENT] (HUB_ID, SRC, IS_DELETED, LOAD_TS)
                 SELECT CONVERT(BINARY(32), HUB_ID, 2), SRC, CAST(IS_DELETED AS BIT), CAST(LOAD_TS AS DATETIME2)
                 FROM #stg_hub_se';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_hub_se;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_hub_se') IS NOT NULL DROP TABLE #stg_hub_se;
    RETURN;
END CATCH

-- === HUB_INVREPORT ===
PRINT 'Loading HUB_INVREPORT...'
BEGIN TRY
    CREATE TABLE #stg_hub_ir (
        HUB_ID   NVARCHAR(64),
        SRC      NVARCHAR(255),
        IS_DELETED NVARCHAR(5),
        LOAD_TS  NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_hub_ir FROM ''' + @CsvPath + N'\hub_invreport.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[HUB_INVREPORT] (HUB_ID, SRC, IS_DELETED, LOAD_TS)
                 SELECT CONVERT(BINARY(32), HUB_ID, 2), SRC, CAST(IS_DELETED AS BIT), CAST(LOAD_TS AS DATETIME2)
                 FROM #stg_hub_ir';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_hub_ir;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_hub_ir') IS NOT NULL DROP TABLE #stg_hub_ir;
    RETURN;
END CATCH

GO

-- =========================================
-- Phase 2: Satellites
-- =========================================
PRINT ''
PRINT '--- Phase 2: Satellites ---'

DECLARE @CsvPath     NVARCHAR(500) = N'C:\threerocks_data\XMS BI\Release\ClaudeDevelopment\demo-data\output';
DECLARE @DatabaseName NVARCHAR(255) = N'20260316_XMS_{GUID}';
DECLARE @sql         NVARCHAR(MAX);

-- === SAT_LOCATION ===
PRINT 'Loading SAT_LOCATION...'
BEGIN TRY
    CREATE TABLE #stg_sat_loc (
        HUB_ID              NVARCHAR(64),
        SRC                 NVARCHAR(255),
        LOAD_TS             NVARCHAR(50),
        EFFECTIVEFROM       NVARCHAR(50),
        EFFECTIVETO         NVARCHAR(50),
        CURRENT_FLAG        NVARCHAR(5),
        IS_DELETED          NVARCHAR(5),
        LOCATION_NAME       NVARCHAR(255),
        PARENT_ID           NVARCHAR(255),
        LEVEL_NAME          NVARCHAR(50),
        BOTTOM_LEVEL        NVARCHAR(5),
        ATTR_1              NVARCHAR(255),
        ATTR_2              NVARCHAR(255),
        ATTR_3              NVARCHAR(255),
        ATTR_4              NVARCHAR(255),
        ATTR_5              NVARCHAR(255),
        LOCATION_ID         NVARCHAR(255),
        MICROSERVICE_ID     NVARCHAR(255),
        MICROSERVICE_NAME   NVARCHAR(255),
        MICROSERVICE_ID_BIN NVARCHAR(64)
    );
    SET @sql = N'BULK INSERT #stg_sat_loc FROM ''' + @CsvPath + N'\sat_location.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_LOCATION]
        (HUB_ID, SRC, LOAD_TS, EFFECTIVEFROM, EFFECTIVETO, CURRENT_FLAG, IS_DELETED,
         LOCATION_NAME, PARENT_ID, LEVEL_NAME, BOTTOM_LEVEL, ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
         LOCATION_ID, MICROSERVICE_ID, MICROSERVICE_NAME, MICROSERVICE_ID_BIN)
        SELECT
            CONVERT(BINARY(32), HUB_ID, 2),
            SRC,
            CAST(LOAD_TS AS DATETIME2),
            CAST(EFFECTIVEFROM AS DATETIME2),
            CAST(EFFECTIVETO AS DATETIME2),
            CAST(CURRENT_FLAG AS BIT),
            CAST(IS_DELETED AS BIT),
            LOCATION_NAME, PARENT_ID, LEVEL_NAME,
            CAST(BOTTOM_LEVEL AS BIT),
            ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
            LOCATION_ID, MICROSERVICE_ID, MICROSERVICE_NAME,
            CONVERT(BINARY(32), MICROSERVICE_ID_BIN, 2)
        FROM #stg_sat_loc';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_sat_loc;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_sat_loc') IS NOT NULL DROP TABLE #stg_sat_loc;
    RETURN;
END CATCH

-- === SAT_PRODUCT ===
PRINT 'Loading SAT_PRODUCT...'
BEGIN TRY
    CREATE TABLE #stg_sat_prod (
        HUB_ID              NVARCHAR(64),
        SRC                 NVARCHAR(255),
        LOAD_TS             NVARCHAR(50),
        EFFECTIVEFROM       NVARCHAR(50),
        EFFECTIVETO         NVARCHAR(50),
        CURRENT_FLAG        NVARCHAR(5),
        IS_DELETED          NVARCHAR(5),
        PRODUCT_NAME        NVARCHAR(255),
        PARENT_ID           NVARCHAR(255),
        LEVEL_NAME          NVARCHAR(50),
        BOTTOM_LEVEL        NVARCHAR(5),
        ATTR_1              NVARCHAR(255),
        ATTR_2              NVARCHAR(255),
        ATTR_3              NVARCHAR(255),
        ATTR_4              NVARCHAR(255),
        ATTR_5              NVARCHAR(255),
        PRODUCT_ID          NVARCHAR(255),
        MICROSERVICE_ID     NVARCHAR(255),
        MICROSERVICE_NAME   NVARCHAR(255),
        MICROSERVICE_ID_BIN NVARCHAR(64)
    );
    SET @sql = N'BULK INSERT #stg_sat_prod FROM ''' + @CsvPath + N'\sat_product.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_PRODUCT]
        (HUB_ID, SRC, LOAD_TS, EFFECTIVEFROM, EFFECTIVETO, CURRENT_FLAG, IS_DELETED,
         PRODUCT_NAME, PARENT_ID, LEVEL_NAME, BOTTOM_LEVEL, ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
         PRODUCT_ID, MICROSERVICE_ID, MICROSERVICE_NAME, MICROSERVICE_ID_BIN)
        SELECT
            CONVERT(BINARY(32), HUB_ID, 2),
            SRC,
            CAST(LOAD_TS AS DATETIME2),
            CAST(EFFECTIVEFROM AS DATETIME2),
            CAST(EFFECTIVETO AS DATETIME2),
            CAST(CURRENT_FLAG AS BIT),
            CAST(IS_DELETED AS BIT),
            PRODUCT_NAME, PARENT_ID, LEVEL_NAME,
            CAST(BOTTOM_LEVEL AS BIT),
            ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
            PRODUCT_ID, MICROSERVICE_ID, MICROSERVICE_NAME,
            CONVERT(BINARY(32), MICROSERVICE_ID_BIN, 2)
        FROM #stg_sat_prod';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_sat_prod;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_sat_prod') IS NOT NULL DROP TABLE #stg_sat_prod;
    RETURN;
END CATCH

-- === SAT_INVITEM ===
PRINT 'Loading SAT_INVITEM...'
BEGIN TRY
    CREATE TABLE #stg_sat_inv (
        HUB_ID              NVARCHAR(64),
        SRC                 NVARCHAR(255),
        LOAD_TS             NVARCHAR(50),
        EFFECTIVEFROM       NVARCHAR(50),
        EFFECTIVETO         NVARCHAR(50),
        CURRENT_FLAG        NVARCHAR(5),
        IS_DELETED          NVARCHAR(5),
        INVITEM_NAME        NVARCHAR(255),
        PARENT_ID           NVARCHAR(255),
        LEVEL_NAME          NVARCHAR(50),
        BOTTOM_LEVEL        NVARCHAR(5),
        ATTR_1              NVARCHAR(255),
        ATTR_2              NVARCHAR(255),
        ATTR_3              NVARCHAR(255),
        ATTR_4              NVARCHAR(255),
        ATTR_5              NVARCHAR(255),
        INVITEM_ID          NVARCHAR(255),
        MICROSERVICE_ID     NVARCHAR(255),
        MICROSERVICE_NAME   NVARCHAR(255),
        MICROSERVICE_ID_BIN NVARCHAR(64),
        UOM                 NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_sat_inv FROM ''' + @CsvPath + N'\sat_invitem.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_INVITEM]
        (HUB_ID, SRC, LOAD_TS, EFFECTIVEFROM, EFFECTIVETO, CURRENT_FLAG, IS_DELETED,
         INVITEM_NAME, PARENT_ID, LEVEL_NAME, BOTTOM_LEVEL, ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
         INVITEM_ID, MICROSERVICE_ID, MICROSERVICE_NAME, MICROSERVICE_ID_BIN, UOM)
        SELECT
            CONVERT(BINARY(32), HUB_ID, 2),
            SRC,
            CAST(LOAD_TS AS DATETIME2),
            CAST(EFFECTIVEFROM AS DATETIME2),
            CAST(EFFECTIVETO AS DATETIME2),
            CAST(CURRENT_FLAG AS BIT),
            CAST(IS_DELETED AS BIT),
            INVITEM_NAME, PARENT_ID, LEVEL_NAME,
            CAST(BOTTOM_LEVEL AS BIT),
            ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
            INVITEM_ID, MICROSERVICE_ID, MICROSERVICE_NAME,
            CONVERT(BINARY(32), MICROSERVICE_ID_BIN, 2),
            UOM
        FROM #stg_sat_inv';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_sat_inv;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_sat_inv') IS NOT NULL DROP TABLE #stg_sat_inv;
    RETURN;
END CATCH

-- === SAT_SUPPLIER ===
PRINT 'Loading SAT_SUPPLIER...'
BEGIN TRY
    CREATE TABLE #stg_sat_sup (
        HUB_ID              NVARCHAR(64),
        SRC                 NVARCHAR(255),
        LOAD_TS             NVARCHAR(50),
        EFFECTIVEFROM       NVARCHAR(50),
        EFFECTIVETO         NVARCHAR(50),
        CURRENT_FLAG        NVARCHAR(5),
        IS_DELETED          NVARCHAR(5),
        SUPPLIER_NAME       NVARCHAR(255),
        PARENT_ID           NVARCHAR(255),
        LEVEL_NAME          NVARCHAR(50),
        BOTTOM_LEVEL        NVARCHAR(5),
        ATTR_1              NVARCHAR(255),
        ATTR_2              NVARCHAR(255),
        ATTR_3              NVARCHAR(255),
        ATTR_4              NVARCHAR(255),
        ATTR_5              NVARCHAR(255),
        SUPPLIER_ID         NVARCHAR(255),
        MICROSERVICE_ID     NVARCHAR(255),
        MICROSERVICE_NAME   NVARCHAR(255),
        MICROSERVICE_ID_BIN NVARCHAR(64)
    );
    SET @sql = N'BULK INSERT #stg_sat_sup FROM ''' + @CsvPath + N'\sat_supplier.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_SUPPLIER]
        (HUB_ID, SRC, LOAD_TS, EFFECTIVEFROM, EFFECTIVETO, CURRENT_FLAG, IS_DELETED,
         SUPPLIER_NAME, PARENT_ID, LEVEL_NAME, BOTTOM_LEVEL, ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
         SUPPLIER_ID, MICROSERVICE_ID, MICROSERVICE_NAME, MICROSERVICE_ID_BIN)
        SELECT
            CONVERT(BINARY(32), HUB_ID, 2),
            SRC,
            CAST(LOAD_TS AS DATETIME2),
            CAST(EFFECTIVEFROM AS DATETIME2),
            CAST(EFFECTIVETO AS DATETIME2),
            CAST(CURRENT_FLAG AS BIT),
            CAST(IS_DELETED AS BIT),
            SUPPLIER_NAME, PARENT_ID, LEVEL_NAME,
            CAST(BOTTOM_LEVEL AS BIT),
            ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
            SUPPLIER_ID, MICROSERVICE_ID, MICROSERVICE_NAME,
            CONVERT(BINARY(32), MICROSERVICE_ID_BIN, 2)
        FROM #stg_sat_sup';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_sat_sup;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_sat_sup') IS NOT NULL DROP TABLE #stg_sat_sup;
    RETURN;
END CATCH

-- === SAT_OCCASION ===
PRINT 'Loading SAT_OCCASION...'
BEGIN TRY
    CREATE TABLE #stg_sat_occ (
        HUB_ID              NVARCHAR(64),
        SRC                 NVARCHAR(255),
        LOAD_TS             NVARCHAR(50),
        EFFECTIVEFROM       NVARCHAR(50),
        EFFECTIVETO         NVARCHAR(50),
        CURRENT_FLAG        NVARCHAR(5),
        IS_DELETED          NVARCHAR(5),
        OCCASION_NAME       NVARCHAR(255),
        PARENT_ID           NVARCHAR(255),
        LEVEL_NAME          NVARCHAR(50),
        BOTTOM_LEVEL        NVARCHAR(5),
        ATTR_1              NVARCHAR(255),
        ATTR_2              NVARCHAR(255),
        ATTR_3              NVARCHAR(255),
        ATTR_4              NVARCHAR(255),
        ATTR_5              NVARCHAR(255),
        OCCASION_ID         NVARCHAR(255),
        MICROSERVICE_ID     NVARCHAR(255),
        MICROSERVICE_NAME   NVARCHAR(255),
        MICROSERVICE_ID_BIN NVARCHAR(64)
    );
    SET @sql = N'BULK INSERT #stg_sat_occ FROM ''' + @CsvPath + N'\sat_occasion.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_OCCASION]
        (HUB_ID, SRC, LOAD_TS, EFFECTIVEFROM, EFFECTIVETO, CURRENT_FLAG, IS_DELETED,
         OCCASION_NAME, PARENT_ID, LEVEL_NAME, BOTTOM_LEVEL, ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
         OCCASION_ID, MICROSERVICE_ID, MICROSERVICE_NAME, MICROSERVICE_ID_BIN)
        SELECT
            CONVERT(BINARY(32), HUB_ID, 2),
            SRC,
            CAST(LOAD_TS AS DATETIME2),
            CAST(EFFECTIVEFROM AS DATETIME2),
            CAST(EFFECTIVETO AS DATETIME2),
            CAST(CURRENT_FLAG AS BIT),
            CAST(IS_DELETED AS BIT),
            OCCASION_NAME, PARENT_ID, LEVEL_NAME,
            CAST(BOTTOM_LEVEL AS BIT),
            ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
            OCCASION_ID, MICROSERVICE_ID, MICROSERVICE_NAME,
            CONVERT(BINARY(32), MICROSERVICE_ID_BIN, 2)
        FROM #stg_sat_occ';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_sat_occ;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_sat_occ') IS NOT NULL DROP TABLE #stg_sat_occ;
    RETURN;
END CATCH

-- === SAT_TENDER ===
PRINT 'Loading SAT_TENDER...'
BEGIN TRY
    CREATE TABLE #stg_sat_tnd (
        HUB_ID              NVARCHAR(64),
        SRC                 NVARCHAR(255),
        LOAD_TS             NVARCHAR(50),
        EFFECTIVEFROM       NVARCHAR(50),
        EFFECTIVETO         NVARCHAR(50),
        CURRENT_FLAG        NVARCHAR(5),
        IS_DELETED          NVARCHAR(5),
        TENDER_NAME         NVARCHAR(255),
        PARENT_ID           NVARCHAR(255),
        LEVEL_NAME          NVARCHAR(50),
        BOTTOM_LEVEL        NVARCHAR(5),
        ATTR_1              NVARCHAR(255),
        ATTR_2              NVARCHAR(255),
        ATTR_3              NVARCHAR(255),
        ATTR_4              NVARCHAR(255),
        ATTR_5              NVARCHAR(255),
        TENDER_ID           NVARCHAR(255),
        MICROSERVICE_ID     NVARCHAR(255),
        MICROSERVICE_NAME   NVARCHAR(255),
        MICROSERVICE_ID_BIN NVARCHAR(64)
    );
    SET @sql = N'BULK INSERT #stg_sat_tnd FROM ''' + @CsvPath + N'\sat_tender.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_TENDER]
        (HUB_ID, SRC, LOAD_TS, EFFECTIVEFROM, EFFECTIVETO, CURRENT_FLAG, IS_DELETED,
         TENDER_NAME, PARENT_ID, LEVEL_NAME, BOTTOM_LEVEL, ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
         TENDER_ID, MICROSERVICE_ID, MICROSERVICE_NAME, MICROSERVICE_ID_BIN)
        SELECT
            CONVERT(BINARY(32), HUB_ID, 2),
            SRC,
            CAST(LOAD_TS AS DATETIME2),
            CAST(EFFECTIVEFROM AS DATETIME2),
            CAST(EFFECTIVETO AS DATETIME2),
            CAST(CURRENT_FLAG AS BIT),
            CAST(IS_DELETED AS BIT),
            TENDER_NAME, PARENT_ID, LEVEL_NAME,
            CAST(BOTTOM_LEVEL AS BIT),
            ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
            TENDER_ID, MICROSERVICE_ID, MICROSERVICE_NAME,
            CONVERT(BINARY(32), MICROSERVICE_ID_BIN, 2)
        FROM #stg_sat_tnd';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_sat_tnd;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_sat_tnd') IS NOT NULL DROP TABLE #stg_sat_tnd;
    RETURN;
END CATCH

-- === SAT_TAX ===
PRINT 'Loading SAT_TAX...'
BEGIN TRY
    CREATE TABLE #stg_sat_tax (
        HUB_ID              NVARCHAR(64),
        SRC                 NVARCHAR(255),
        LOAD_TS             NVARCHAR(50),
        EFFECTIVEFROM       NVARCHAR(50),
        EFFECTIVETO         NVARCHAR(50),
        CURRENT_FLAG        NVARCHAR(5),
        IS_DELETED          NVARCHAR(5),
        TAX_NAME            NVARCHAR(255),
        PARENT_ID           NVARCHAR(255),
        LEVEL_NAME          NVARCHAR(50),
        BOTTOM_LEVEL        NVARCHAR(5),
        ATTR_1              NVARCHAR(255),
        ATTR_2              NVARCHAR(255),
        ATTR_3              NVARCHAR(255),
        ATTR_4              NVARCHAR(255),
        ATTR_5              NVARCHAR(255),
        TAX_ID              NVARCHAR(255),
        MICROSERVICE_ID     NVARCHAR(255),
        MICROSERVICE_NAME   NVARCHAR(255),
        MICROSERVICE_ID_BIN NVARCHAR(64)
    );
    SET @sql = N'BULK INSERT #stg_sat_tax FROM ''' + @CsvPath + N'\sat_tax.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_TAX]
        (HUB_ID, SRC, LOAD_TS, EFFECTIVEFROM, EFFECTIVETO, CURRENT_FLAG, IS_DELETED,
         TAX_NAME, PARENT_ID, LEVEL_NAME, BOTTOM_LEVEL, ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
         TAX_ID, MICROSERVICE_ID, MICROSERVICE_NAME, MICROSERVICE_ID_BIN)
        SELECT
            CONVERT(BINARY(32), HUB_ID, 2),
            SRC,
            CAST(LOAD_TS AS DATETIME2),
            CAST(EFFECTIVEFROM AS DATETIME2),
            CAST(EFFECTIVETO AS DATETIME2),
            CAST(CURRENT_FLAG AS BIT),
            CAST(IS_DELETED AS BIT),
            TAX_NAME, PARENT_ID, LEVEL_NAME,
            CAST(BOTTOM_LEVEL AS BIT),
            ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
            TAX_ID, MICROSERVICE_ID, MICROSERVICE_NAME,
            CONVERT(BINARY(32), MICROSERVICE_ID_BIN, 2)
        FROM #stg_sat_tax';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_sat_tax;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_sat_tax') IS NOT NULL DROP TABLE #stg_sat_tax;
    RETURN;
END CATCH

-- === SAT_REVCENTER ===
PRINT 'Loading SAT_REVCENTER...'
BEGIN TRY
    CREATE TABLE #stg_sat_rev (
        HUB_ID              NVARCHAR(64),
        SRC                 NVARCHAR(255),
        LOAD_TS             NVARCHAR(50),
        EFFECTIVEFROM       NVARCHAR(50),
        EFFECTIVETO         NVARCHAR(50),
        CURRENT_FLAG        NVARCHAR(5),
        IS_DELETED          NVARCHAR(5),
        REVCENTER_NAME      NVARCHAR(255),
        PARENT_ID           NVARCHAR(255),
        LEVEL_NAME          NVARCHAR(50),
        BOTTOM_LEVEL        NVARCHAR(5),
        ATTR_1              NVARCHAR(255),
        ATTR_2              NVARCHAR(255),
        ATTR_3              NVARCHAR(255),
        ATTR_4              NVARCHAR(255),
        ATTR_5              NVARCHAR(255),
        REVCENTER_ID        NVARCHAR(255),
        MICROSERVICE_ID     NVARCHAR(255),
        MICROSERVICE_NAME   NVARCHAR(255),
        MICROSERVICE_ID_BIN NVARCHAR(64)
    );
    SET @sql = N'BULK INSERT #stg_sat_rev FROM ''' + @CsvPath + N'\sat_revcenter.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_REVCENTER]
        (HUB_ID, SRC, LOAD_TS, EFFECTIVEFROM, EFFECTIVETO, CURRENT_FLAG, IS_DELETED,
         REVCENTER_NAME, PARENT_ID, LEVEL_NAME, BOTTOM_LEVEL, ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
         REVCENTER_ID, MICROSERVICE_ID, MICROSERVICE_NAME, MICROSERVICE_ID_BIN)
        SELECT
            CONVERT(BINARY(32), HUB_ID, 2),
            SRC,
            CAST(LOAD_TS AS DATETIME2),
            CAST(EFFECTIVEFROM AS DATETIME2),
            CAST(EFFECTIVETO AS DATETIME2),
            CAST(CURRENT_FLAG AS BIT),
            CAST(IS_DELETED AS BIT),
            REVCENTER_NAME, PARENT_ID, LEVEL_NAME,
            CAST(BOTTOM_LEVEL AS BIT),
            ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
            REVCENTER_ID, MICROSERVICE_ID, MICROSERVICE_NAME,
            CONVERT(BINARY(32), MICROSERVICE_ID_BIN, 2)
        FROM #stg_sat_rev';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_sat_rev;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_sat_rev') IS NOT NULL DROP TABLE #stg_sat_rev;
    RETURN;
END CATCH

-- === SAT_DISCOUNT ===
PRINT 'Loading SAT_DISCOUNT...'
BEGIN TRY
    CREATE TABLE #stg_sat_dis (
        HUB_ID              NVARCHAR(64),
        SRC                 NVARCHAR(255),
        LOAD_TS             NVARCHAR(50),
        EFFECTIVEFROM       NVARCHAR(50),
        EFFECTIVETO         NVARCHAR(50),
        CURRENT_FLAG        NVARCHAR(5),
        IS_DELETED          NVARCHAR(5),
        DISCOUNT_NAME       NVARCHAR(255),
        PARENT_ID           NVARCHAR(255),
        LEVEL_NAME          NVARCHAR(50),
        BOTTOM_LEVEL        NVARCHAR(5),
        ATTR_1              NVARCHAR(255),
        ATTR_2              NVARCHAR(255),
        ATTR_3              NVARCHAR(255),
        ATTR_4              NVARCHAR(255),
        ATTR_5              NVARCHAR(255),
        DISCOUNT_ID         NVARCHAR(255),
        MICROSERVICE_ID     NVARCHAR(255),
        MICROSERVICE_NAME   NVARCHAR(255),
        MICROSERVICE_ID_BIN NVARCHAR(64)
    );
    SET @sql = N'BULK INSERT #stg_sat_dis FROM ''' + @CsvPath + N'\sat_discount.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_DISCOUNT]
        (HUB_ID, SRC, LOAD_TS, EFFECTIVEFROM, EFFECTIVETO, CURRENT_FLAG, IS_DELETED,
         DISCOUNT_NAME, PARENT_ID, LEVEL_NAME, BOTTOM_LEVEL, ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
         DISCOUNT_ID, MICROSERVICE_ID, MICROSERVICE_NAME, MICROSERVICE_ID_BIN)
        SELECT
            CONVERT(BINARY(32), HUB_ID, 2),
            SRC,
            CAST(LOAD_TS AS DATETIME2),
            CAST(EFFECTIVEFROM AS DATETIME2),
            CAST(EFFECTIVETO AS DATETIME2),
            CAST(CURRENT_FLAG AS BIT),
            CAST(IS_DELETED AS BIT),
            DISCOUNT_NAME, PARENT_ID, LEVEL_NAME,
            CAST(BOTTOM_LEVEL AS BIT),
            ATTR_1, ATTR_2, ATTR_3, ATTR_4, ATTR_5,
            DISCOUNT_ID, MICROSERVICE_ID, MICROSERVICE_NAME,
            CONVERT(BINARY(32), MICROSERVICE_ID_BIN, 2)
        FROM #stg_sat_dis';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_sat_dis;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_sat_dis') IS NOT NULL DROP TABLE #stg_sat_dis;
    RETURN;
END CATCH

-- === SAT_EMPLOYEE ===
PRINT 'Loading SAT_EMPLOYEE...'
BEGIN TRY
    CREATE TABLE #stg_sat_emp (
        HUB_ID              NVARCHAR(64),
        SRC                 NVARCHAR(255),
        LOAD_TS             NVARCHAR(50),
        EFFECTIVEFROM       NVARCHAR(50),
        EFFECTIVETO         NVARCHAR(50),
        CURRENT_FLAG        NVARCHAR(5),
        IS_DELETED          NVARCHAR(5),
        SURNAME             NVARCHAR(255),
        FIRST_NAME          NVARCHAR(255),
        MIDDLE_NAME         NVARCHAR(255),
        POST_DESC           NVARCHAR(255),
        ACTIVE_DATE         NVARCHAR(50),
        END_DATE            NVARCHAR(50),
        PAYTYPE             NVARCHAR(50),
        TRONC_OPTOUT_DATE   NVARCHAR(50),
        MICROSERVICE_ID     NVARCHAR(255),
        MICROSERVICE_NAME   NVARCHAR(255),
        MICROSERVICE_ID_BIN NVARCHAR(64)
    );
    SET @sql = N'BULK INSERT #stg_sat_emp FROM ''' + @CsvPath + N'\sat_employee.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_EMPLOYEE]
        (HUB_ID, SRC, LOAD_TS, EFFECTIVEFROM, EFFECTIVETO, CURRENT_FLAG, IS_DELETED,
         SURNAME, FIRST_NAME, MIDDLE_NAME, POST_DESC,
         ACTIVE_DATE, END_DATE, PAYTYPE, TRONC_OPTOUT_DATE,
         MICROSERVICE_ID, MICROSERVICE_NAME, MICROSERVICE_ID_BIN)
        SELECT
            CONVERT(BINARY(32), HUB_ID, 2),
            SRC,
            CAST(LOAD_TS AS DATETIME2),
            CAST(EFFECTIVEFROM AS DATETIME2),
            CAST(EFFECTIVETO AS DATETIME2),
            CAST(CURRENT_FLAG AS BIT),
            CAST(IS_DELETED AS BIT),
            SURNAME, FIRST_NAME, MIDDLE_NAME, POST_DESC,
            CASE WHEN NULLIF(ACTIVE_DATE, N'''') IS NULL THEN NULL ELSE CAST(ACTIVE_DATE AS DECIMAL(18,2)) END,
            CASE WHEN NULLIF(END_DATE, N'''') IS NULL THEN NULL ELSE CAST(END_DATE AS DATETIME2) END,
            PAYTYPE,
            CASE WHEN NULLIF(TRONC_OPTOUT_DATE, N'''') IS NULL THEN NULL ELSE CAST(TRONC_OPTOUT_DATE AS DATETIME2) END,
            MICROSERVICE_ID, MICROSERVICE_NAME,
            CONVERT(BINARY(32), MICROSERVICE_ID_BIN, 2)
        FROM #stg_sat_emp';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_sat_emp;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_sat_emp') IS NOT NULL DROP TABLE #stg_sat_emp;
    RETURN;
END CATCH

-- === SAT_CUSTORDER ===
PRINT 'Loading SAT_CUSTORDER...'
BEGIN TRY
    CREATE TABLE #stg_sat_co (
        HUB_ID               NVARCHAR(64),
        SRC                  NVARCHAR(255),
        LOAD_TS              NVARCHAR(50),
        EFFECTIVEFROM        NVARCHAR(50),
        EFFECTIVETO          NVARCHAR(50),
        CURRENT_FLAG         NVARCHAR(5),
        IS_DELETED           NVARCHAR(5),
        GRAND_TOTAL          NVARCHAR(50),
        GRAND_TOTAL_SRC      NVARCHAR(50),
        DISCOUNT_GROSS       NVARCHAR(50),
        DISCOUNT_GROSS_SRC   NVARCHAR(50),
        SVC_CHARGE_TOTAL     NVARCHAR(50),
        SVC_CHARGE_TOTAL_SRC NVARCHAR(50),
        GROSS_SALES          NVARCHAR(50),
        GROSS_SALES_SRC      NVARCHAR(50),
        TAX_TOTAL            NVARCHAR(50),
        TAX_TOTAL_SRC        NVARCHAR(50),
        NET_SALES            NVARCHAR(50),
        NET_SALES_SRC        NVARCHAR(50),
        GUEST_COUNT          NVARCHAR(50),
        ITEM_COUNT           NVARCHAR(50),
        ITEM_COUNT_SRC       NVARCHAR(50),
        ORDER_COUNT          NVARCHAR(50),
        OPEN_TIME            NVARCHAR(50),
        CLOSE_TIME           NVARCHAR(50),
        ORDER_DATE           NVARCHAR(50),
        TABLE_NO             NVARCHAR(255),
        ORDER_INFO           NVARCHAR(255),
        EXTERNAL_REFERENCE   NVARCHAR(255),
        ORDER_STATUS         NVARCHAR(50),
        PAYMENT_STATUS       NVARCHAR(50),
        DISCOUNT_NET         NVARCHAR(50),
        DISCOUNT_NET_SRC     NVARCHAR(50),
        DISCOUNT_TAX         NVARCHAR(50),
        DISCOUNT_TAX_SRC     NVARCHAR(50),
        TENDERED_SALES       NVARCHAR(50),
        TRADING_DATE         NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_sat_co FROM ''' + @CsvPath + N'\sat_custorder.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_CUSTORDER]
        (HUB_ID, SRC, LOAD_TS, EFFECTIVEFROM, EFFECTIVETO, CURRENT_FLAG, IS_DELETED,
         GRAND_TOTAL, GRAND_TOTAL_SRC, DISCOUNT_GROSS, DISCOUNT_GROSS_SRC,
         SVC_CHARGE_TOTAL, SVC_CHARGE_TOTAL_SRC, GROSS_SALES, GROSS_SALES_SRC,
         TAX_TOTAL, TAX_TOTAL_SRC, NET_SALES, NET_SALES_SRC,
         GUEST_COUNT, ITEM_COUNT, ITEM_COUNT_SRC, ORDER_COUNT,
         OPEN_TIME, CLOSE_TIME, ORDER_DATE, TABLE_NO, ORDER_INFO,
         EXTERNAL_REFERENCE, ORDER_STATUS, PAYMENT_STATUS,
         DISCOUNT_NET, DISCOUNT_NET_SRC, DISCOUNT_TAX, DISCOUNT_TAX_SRC,
         TENDERED_SALES, TRADING_DATE)
        SELECT
            CONVERT(BINARY(32), HUB_ID, 2),
            SRC,
            CAST(LOAD_TS AS DATETIME2),
            CAST(EFFECTIVEFROM AS DATETIME2),
            CAST(EFFECTIVETO AS DATETIME2),
            CAST(CURRENT_FLAG AS BIT),
            CAST(IS_DELETED AS BIT),
            CAST(GRAND_TOTAL AS DECIMAL(18,4)),
            CAST(GRAND_TOTAL_SRC AS DECIMAL(18,4)),
            CAST(DISCOUNT_GROSS AS DECIMAL(18,4)),
            CAST(DISCOUNT_GROSS_SRC AS DECIMAL(18,4)),
            CAST(SVC_CHARGE_TOTAL AS DECIMAL(18,4)),
            CAST(SVC_CHARGE_TOTAL_SRC AS DECIMAL(18,4)),
            CAST(GROSS_SALES AS DECIMAL(18,4)),
            CAST(GROSS_SALES_SRC AS DECIMAL(18,4)),
            CAST(TAX_TOTAL AS DECIMAL(18,4)),
            CAST(TAX_TOTAL_SRC AS DECIMAL(18,4)),
            CAST(NET_SALES AS DECIMAL(18,4)),
            CAST(NET_SALES_SRC AS DECIMAL(18,4)),
            CAST(GUEST_COUNT AS INT),
            CAST(ITEM_COUNT AS INT),
            CAST(ITEM_COUNT_SRC AS INT),
            CAST(ORDER_COUNT AS INT),
            CASE WHEN NULLIF(OPEN_TIME, N'''') IS NULL THEN NULL ELSE CAST(OPEN_TIME AS DATETIME2) END,
            CASE WHEN NULLIF(CLOSE_TIME, N'''') IS NULL THEN NULL ELSE CAST(CLOSE_TIME AS DATETIME2) END,
            CASE WHEN NULLIF(ORDER_DATE, N'''') IS NULL THEN NULL ELSE CAST(ORDER_DATE AS DATETIME2) END,
            TABLE_NO, ORDER_INFO, EXTERNAL_REFERENCE, ORDER_STATUS, PAYMENT_STATUS,
            CAST(DISCOUNT_NET AS DECIMAL(18,4)),
            CAST(DISCOUNT_NET_SRC AS DECIMAL(18,4)),
            CAST(DISCOUNT_TAX AS DECIMAL(18,4)),
            CAST(DISCOUNT_TAX_SRC AS DECIMAL(18,4)),
            CAST(TENDERED_SALES AS DECIMAL(18,4)),
            CASE WHEN NULLIF(TRADING_DATE, N'''') IS NULL THEN NULL ELSE CAST(TRADING_DATE AS DATE) END
        FROM #stg_sat_co';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_sat_co;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_sat_co') IS NOT NULL DROP TABLE #stg_sat_co;
    RETURN;
END CATCH

-- === SAT_LINEITEM ===
PRINT 'Loading SAT_LINEITEM...'
BEGIN TRY
    CREATE TABLE #stg_sat_li (
        HUB_ID             NVARCHAR(64),
        SRC                NVARCHAR(255),
        LOAD_TS            NVARCHAR(50),
        EFFECTIVEFROM      NVARCHAR(50),
        EFFECTIVETO        NVARCHAR(50),
        CURRENT_FLAG       NVARCHAR(5),
        IS_DELETED         NVARCHAR(5),
        HEADER_ID          NVARCHAR(255),
        LINEITEM_TYPE      NVARCHAR(50),
        GROSS_VALUE        NVARCHAR(50),
        TAX_VALUE          NVARCHAR(50),
        NET_VALUE          NVARCHAR(50),
        QUANTITY           NVARCHAR(50),
        QUANTITY_INV       NVARCHAR(50),
        LINEITEM_TIMESTAMP NVARCHAR(50),
        ITEM_DATE          NVARCHAR(50),
        ORDER_DATE         NVARCHAR(50),
        VOID_FLAG          NVARCHAR(5),
        LINE_ID            NVARCHAR(255),
        LINE_ORDER         NVARCHAR(50),
        TRADING_DATE       NVARCHAR(50),
        SRC_KEY            NVARCHAR(255)
    );
    SET @sql = N'BULK INSERT #stg_sat_li FROM ''' + @CsvPath + N'\sat_lineitem.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_LINEITEM]
        (HUB_ID, SRC, LOAD_TS, EFFECTIVEFROM, EFFECTIVETO, CURRENT_FLAG, IS_DELETED,
         HEADER_ID, LINEITEM_TYPE, GROSS_VALUE, TAX_VALUE, NET_VALUE,
         QUANTITY, QUANTITY_INV, LINEITEM_TIMESTAMP, ITEM_DATE, ORDER_DATE,
         VOID_FLAG, LINE_ID, LINE_ORDER, TRADING_DATE, SRC_KEY)
        SELECT
            CONVERT(BINARY(32), HUB_ID, 2),
            SRC,
            CAST(LOAD_TS AS DATETIME2),
            CAST(EFFECTIVEFROM AS DATETIME2),
            CAST(EFFECTIVETO AS DATETIME2),
            CAST(CURRENT_FLAG AS BIT),
            CAST(IS_DELETED AS BIT),
            HEADER_ID, LINEITEM_TYPE,
            CAST(GROSS_VALUE AS DECIMAL(18,4)),
            CAST(TAX_VALUE AS DECIMAL(18,4)),
            CAST(NET_VALUE AS DECIMAL(18,4)),
            CAST(QUANTITY AS DECIMAL(18,4)),
            CAST(QUANTITY_INV AS DECIMAL(18,4)),
            CASE WHEN NULLIF(LINEITEM_TIMESTAMP, N'''') IS NULL THEN NULL ELSE CAST(LINEITEM_TIMESTAMP AS DATETIME2) END,
            CASE WHEN NULLIF(ITEM_DATE, N'''') IS NULL THEN NULL ELSE CAST(ITEM_DATE AS DATE) END,
            CASE WHEN NULLIF(ORDER_DATE, N'''') IS NULL THEN NULL ELSE CAST(ORDER_DATE AS DATETIME2) END,
            CAST(VOID_FLAG AS BIT),
            LINE_ID,
            CAST(LINE_ORDER AS INT),
            CASE WHEN NULLIF(TRADING_DATE, N'''') IS NULL THEN NULL ELSE CAST(TRADING_DATE AS DATE) END,
            SRC_KEY
        FROM #stg_sat_li';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_sat_li;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_sat_li') IS NOT NULL DROP TABLE #stg_sat_li;
    RETURN;
END CATCH

-- === SAT_STOCKEVENT ===
PRINT 'Loading SAT_STOCKEVENT...'
BEGIN TRY
    CREATE TABLE #stg_sat_se (
        HUB_ID          NVARCHAR(64),
        SRC             NVARCHAR(255),
        LOAD_TS         NVARCHAR(50),
        EFFECTIVEFROM   NVARCHAR(50),
        EFFECTIVETO     NVARCHAR(50),
        CURRENT_FLAG    NVARCHAR(5),
        IS_DELETED      NVARCHAR(5),
        EVENT_TYPE      NVARCHAR(50),
        EVENT_TS        NVARCHAR(50),
        PACK_DESC       NVARCHAR(255),
        PACK_QUANTITY   NVARCHAR(50),
        UOM             NVARCHAR(50),
        UOM_QUANITY     NVARCHAR(50),
        EXTERNAL_REF    NVARCHAR(255),
        INTERNAL_REF    NVARCHAR(255),
        EVENT_BEHAVIOUR NVARCHAR(10)
    );
    SET @sql = N'BULK INSERT #stg_sat_se FROM ''' + @CsvPath + N'\sat_stockevent.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_STOCKEVENT]
        (HUB_ID, SRC, LOAD_TS, EFFECTIVEFROM, EFFECTIVETO, CURRENT_FLAG, IS_DELETED,
         EVENT_TYPE, EVENT_TS, PACK_DESC, PACK_QUANTITY, UOM, UOM_QUANITY,
         EXTERNAL_REF, INTERNAL_REF, EVENT_BEHAVIOUR)
        SELECT
            CONVERT(BINARY(32), HUB_ID, 2),
            SRC,
            CAST(LOAD_TS AS DATETIME2),
            CAST(EFFECTIVEFROM AS DATETIME2),
            CAST(EFFECTIVETO AS DATETIME2),
            CAST(CURRENT_FLAG AS BIT),
            CAST(IS_DELETED AS BIT),
            EVENT_TYPE,
            CASE WHEN NULLIF(EVENT_TS, N'''') IS NULL THEN NULL ELSE CAST(EVENT_TS AS DATETIME2) END,
            PACK_DESC,
            CAST(PACK_QUANTITY AS DECIMAL(18,4)),
            UOM,
            CAST(UOM_QUANITY AS DECIMAL(18,4)),
            EXTERNAL_REF, INTERNAL_REF, EVENT_BEHAVIOUR
        FROM #stg_sat_se';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_sat_se;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_sat_se') IS NOT NULL DROP TABLE #stg_sat_se;
    RETURN;
END CATCH

-- === SAT_INVREPORT ===
PRINT 'Loading SAT_INVREPORT...'
BEGIN TRY
    CREATE TABLE #stg_sat_ir (
        HUB_ID          NVARCHAR(64),
        SRC             NVARCHAR(255),
        LOAD_TS         NVARCHAR(50),
        EFFECTIVEFROM   NVARCHAR(50),
        EFFECTIVETO     NVARCHAR(50),
        CURRENT_FLAG    NVARCHAR(5),
        IS_DELETED      NVARCHAR(5),
        THEO_USAGE      NVARCHAR(50),
        ACTUAL_USAGE    NVARCHAR(50),
        THEO_COST       NVARCHAR(50),
        ACTUAL_COST     NVARCHAR(50),
        VARIANCE_QTY    NVARCHAR(50),
        VARIANCE_VALUE  NVARCHAR(50),
        WASTE_QTY       NVARCHAR(50),
        WASTE_VALUE     NVARCHAR(50),
        REPORTING_DATE  NVARCHAR(50),
        REPORTING_UOM   NVARCHAR(50),
        UOM_COST        NVARCHAR(50),
        SALES_QTY       NVARCHAR(50),
        ORDER_QTY       NVARCHAR(50),
        TRANSFER_QTY    NVARCHAR(50),
        COUNT_FREQUENCY NVARCHAR(50),
        COUNT_RECENCY   NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_sat_ir FROM ''' + @CsvPath + N'\sat_invreport.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_INVREPORT]
        (HUB_ID, SRC, LOAD_TS, EFFECTIVEFROM, EFFECTIVETO, CURRENT_FLAG, IS_DELETED,
         THEO_USAGE, ACTUAL_USAGE, THEO_COST, ACTUAL_COST,
         VARIANCE_QTY, VARIANCE_VALUE, WASTE_QTY, WASTE_VALUE,
         REPORTING_DATE, REPORTING_UOM, UOM_COST,
         SALES_QTY, ORDER_QTY, TRANSFER_QTY, COUNT_FREQUENCY, COUNT_RECENCY)
        SELECT
            CONVERT(BINARY(32), HUB_ID, 2),
            SRC,
            CAST(LOAD_TS AS DATETIME2),
            CAST(EFFECTIVEFROM AS DATETIME2),
            CAST(EFFECTIVETO AS DATETIME2),
            CAST(CURRENT_FLAG AS BIT),
            CAST(IS_DELETED AS BIT),
            CAST(THEO_USAGE AS DECIMAL(18,4)),
            CAST(ACTUAL_USAGE AS DECIMAL(18,4)),
            CAST(THEO_COST AS DECIMAL(18,4)),
            CAST(ACTUAL_COST AS DECIMAL(18,4)),
            CAST(VARIANCE_QTY AS DECIMAL(18,4)),
            CAST(VARIANCE_VALUE AS DECIMAL(18,4)),
            CAST(WASTE_QTY AS DECIMAL(18,4)),
            CAST(WASTE_VALUE AS DECIMAL(18,4)),
            CASE WHEN NULLIF(REPORTING_DATE, N'''') IS NULL THEN NULL ELSE CAST(REPORTING_DATE AS DATE) END,
            REPORTING_UOM,
            CAST(UOM_COST AS DECIMAL(18,4)),
            CAST(SALES_QTY AS DECIMAL(18,4)),
            CAST(ORDER_QTY AS DECIMAL(18,4)),
            CAST(TRANSFER_QTY AS DECIMAL(18,4)),
            CAST(COUNT_FREQUENCY AS INT),
            CASE WHEN NULLIF(COUNT_RECENCY, N'''') IS NULL THEN NULL ELSE CAST(COUNT_RECENCY AS DATE) END
        FROM #stg_sat_ir';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_sat_ir;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_sat_ir') IS NOT NULL DROP TABLE #stg_sat_ir;
    RETURN;
END CATCH

GO

-- =========================================
-- Phase 3: Links
-- =========================================
PRINT ''
PRINT '--- Phase 3: Links ---'

DECLARE @CsvPath     NVARCHAR(500) = N'C:\threerocks_data\XMS BI\Release\ClaudeDevelopment\demo-data\output';
DECLARE @DatabaseName NVARCHAR(255) = N'20260316_XMS_{GUID}';
DECLARE @sql         NVARCHAR(MAX);

-- === LNK_CUSTORDER_LOCATION ===
PRINT 'Loading LNK_CUSTORDER_LOCATION...'
BEGIN TRY
    CREATE TABLE #stg_lnk_col (
        LNK_ID           NVARCHAR(64),
        SRC              NVARCHAR(255),
        LOAD_TS          NVARCHAR(50),
        CUSTORDER_HUB_ID NVARCHAR(64),
        LOCATION_HUB_ID  NVARCHAR(64),
        CUSTORDER_AGG    NVARCHAR(50),
        LOCATION_AGG     NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_col FROM ''' + @CsvPath + N'\lnk_custorder_location.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_CUSTORDER_LOCATION]
        (LNK_ID, SRC, LOAD_TS, CUSTORDER_HUB_ID, LOCATION_HUB_ID, CUSTORDER_AGG, LOCATION_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),CUSTORDER_HUB_ID,2), CONVERT(BINARY(32),LOCATION_HUB_ID,2),
               CAST(CUSTORDER_AGG AS INT), CAST(LOCATION_AGG AS INT)
        FROM #stg_lnk_col';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_col;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_col') IS NOT NULL DROP TABLE #stg_lnk_col;
    RETURN;
END CATCH

-- === LNK_CUSTORDER_EMPLOYEE ===
PRINT 'Loading LNK_CUSTORDER_EMPLOYEE...'
BEGIN TRY
    CREATE TABLE #stg_lnk_coe (
        LNK_ID           NVARCHAR(64),
        SRC              NVARCHAR(255),
        LOAD_TS          NVARCHAR(50),
        CUSTORDER_HUB_ID NVARCHAR(64),
        EMPLOYEE_HUB_ID  NVARCHAR(64),
        CUSTORDER_AGG    NVARCHAR(50),
        EMPLOYEE_AGG     NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_coe FROM ''' + @CsvPath + N'\lnk_custorder_employee.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_CUSTORDER_EMPLOYEE]
        (LNK_ID, SRC, LOAD_TS, CUSTORDER_HUB_ID, EMPLOYEE_HUB_ID, CUSTORDER_AGG, EMPLOYEE_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),CUSTORDER_HUB_ID,2), CONVERT(BINARY(32),EMPLOYEE_HUB_ID,2),
               CAST(CUSTORDER_AGG AS INT), CAST(EMPLOYEE_AGG AS INT)
        FROM #stg_lnk_coe';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_coe;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_coe') IS NOT NULL DROP TABLE #stg_lnk_coe;
    RETURN;
END CATCH

-- === LNK_CUSTORDER_LINEITEM ===
PRINT 'Loading LNK_CUSTORDER_LINEITEM...'
BEGIN TRY
    CREATE TABLE #stg_lnk_cli (
        LNK_ID           NVARCHAR(64),
        SRC              NVARCHAR(255),
        LOAD_TS          NVARCHAR(50),
        CUSTORDER_HUB_ID NVARCHAR(64),
        LINEITEM_HUB_ID  NVARCHAR(64),
        CUSTORDER_AGG    NVARCHAR(50),
        LINEITEM_AGG     NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_cli FROM ''' + @CsvPath + N'\lnk_custorder_lineitem.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_CUSTORDER_LINEITEM]
        (LNK_ID, SRC, LOAD_TS, CUSTORDER_HUB_ID, LINEITEM_HUB_ID, CUSTORDER_AGG, LINEITEM_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),CUSTORDER_HUB_ID,2), CONVERT(BINARY(32),LINEITEM_HUB_ID,2),
               CAST(CUSTORDER_AGG AS INT), CAST(LINEITEM_AGG AS INT)
        FROM #stg_lnk_cli';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_cli;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_cli') IS NOT NULL DROP TABLE #stg_lnk_cli;
    RETURN;
END CATCH

-- === LNK_CUSTORDER_OCCASION ===
PRINT 'Loading LNK_CUSTORDER_OCCASION...'
BEGIN TRY
    CREATE TABLE #stg_lnk_coo (
        LNK_ID           NVARCHAR(64),
        SRC              NVARCHAR(255),
        LOAD_TS          NVARCHAR(50),
        CUSTORDER_HUB_ID NVARCHAR(64),
        OCCASION_HUB_ID  NVARCHAR(64),
        CUSTORDER_AGG    NVARCHAR(50),
        OCCASION_AGG     NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_coo FROM ''' + @CsvPath + N'\lnk_custorder_occasion.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_CUSTORDER_OCCASION]
        (LNK_ID, SRC, LOAD_TS, CUSTORDER_HUB_ID, OCCASION_HUB_ID, CUSTORDER_AGG, OCCASION_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),CUSTORDER_HUB_ID,2), CONVERT(BINARY(32),OCCASION_HUB_ID,2),
               CAST(CUSTORDER_AGG AS INT), CAST(OCCASION_AGG AS INT)
        FROM #stg_lnk_coo';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_coo;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_coo') IS NOT NULL DROP TABLE #stg_lnk_coo;
    RETURN;
END CATCH

-- === LNK_CUSTORDER_REVCENTER ===
PRINT 'Loading LNK_CUSTORDER_REVCENTER...'
BEGIN TRY
    CREATE TABLE #stg_lnk_cor (
        LNK_ID            NVARCHAR(64),
        SRC               NVARCHAR(255),
        LOAD_TS           NVARCHAR(50),
        CUSTORDER_HUB_ID  NVARCHAR(64),
        REVCENTER_HUB_ID  NVARCHAR(64),
        CUSTORDER_AGG     NVARCHAR(50),
        REVCENTER_AGG     NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_cor FROM ''' + @CsvPath + N'\lnk_custorder_revcenter.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_CUSTORDER_REVCENTER]
        (LNK_ID, SRC, LOAD_TS, CUSTORDER_HUB_ID, REVCENTER_HUB_ID, CUSTORDER_AGG, REVCENTER_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),CUSTORDER_HUB_ID,2), CONVERT(BINARY(32),REVCENTER_HUB_ID,2),
               CAST(CUSTORDER_AGG AS INT), CAST(REVCENTER_AGG AS INT)
        FROM #stg_lnk_cor';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_cor;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_cor') IS NOT NULL DROP TABLE #stg_lnk_cor;
    RETURN;
END CATCH

-- === LNK_LINEITEM_PRODUCT ===
PRINT 'Loading LNK_LINEITEM_PRODUCT...'
BEGIN TRY
    CREATE TABLE #stg_lnk_lip (
        LNK_ID          NVARCHAR(64),
        SRC             NVARCHAR(255),
        LOAD_TS         NVARCHAR(50),
        LINEITEM_HUB_ID NVARCHAR(64),
        PRODUCT_HUB_ID  NVARCHAR(64),
        LINEITEM_AGG    NVARCHAR(50),
        PRODUCT_AGG     NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_lip FROM ''' + @CsvPath + N'\lnk_lineitem_product.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_LINEITEM_PRODUCT]
        (LNK_ID, SRC, LOAD_TS, LINEITEM_HUB_ID, PRODUCT_HUB_ID, LINEITEM_AGG, PRODUCT_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),LINEITEM_HUB_ID,2), CONVERT(BINARY(32),PRODUCT_HUB_ID,2),
               CAST(LINEITEM_AGG AS INT), CAST(PRODUCT_AGG AS INT)
        FROM #stg_lnk_lip';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_lip;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_lip') IS NOT NULL DROP TABLE #stg_lnk_lip;
    RETURN;
END CATCH

-- === LNK_LINEITEM_TAX ===
PRINT 'Loading LNK_LINEITEM_TAX...'
BEGIN TRY
    CREATE TABLE #stg_lnk_lit (
        LNK_ID          NVARCHAR(64),
        SRC             NVARCHAR(255),
        LOAD_TS         NVARCHAR(50),
        LINEITEM_HUB_ID NVARCHAR(64),
        TAX_HUB_ID      NVARCHAR(64),
        LINEITEM_AGG    NVARCHAR(50),
        TAX_AGG         NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_lit FROM ''' + @CsvPath + N'\lnk_lineitem_tax.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_LINEITEM_TAX]
        (LNK_ID, SRC, LOAD_TS, LINEITEM_HUB_ID, TAX_HUB_ID, LINEITEM_AGG, TAX_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),LINEITEM_HUB_ID,2), CONVERT(BINARY(32),TAX_HUB_ID,2),
               CAST(LINEITEM_AGG AS INT), CAST(TAX_AGG AS INT)
        FROM #stg_lnk_lit';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_lit;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_lit') IS NOT NULL DROP TABLE #stg_lnk_lit;
    RETURN;
END CATCH

-- === LNK_LINEITEM_OCCASION ===
PRINT 'Loading LNK_LINEITEM_OCCASION...'
BEGIN TRY
    CREATE TABLE #stg_lnk_lio (
        LNK_ID          NVARCHAR(64),
        SRC             NVARCHAR(255),
        LOAD_TS         NVARCHAR(50),
        LINEITEM_HUB_ID NVARCHAR(64),
        OCCASION_HUB_ID NVARCHAR(64),
        LINEITEM_AGG    NVARCHAR(50),
        OCCASION_AGG    NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_lio FROM ''' + @CsvPath + N'\lnk_lineitem_occasion.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_LINEITEM_OCCASION]
        (LNK_ID, SRC, LOAD_TS, LINEITEM_HUB_ID, OCCASION_HUB_ID, LINEITEM_AGG, OCCASION_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),LINEITEM_HUB_ID,2), CONVERT(BINARY(32),OCCASION_HUB_ID,2),
               CAST(LINEITEM_AGG AS INT), CAST(OCCASION_AGG AS INT)
        FROM #stg_lnk_lio';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_lio;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_lio') IS NOT NULL DROP TABLE #stg_lnk_lio;
    RETURN;
END CATCH

-- === LNK_EMPLOYEE_LINEITEM ===
PRINT 'Loading LNK_EMPLOYEE_LINEITEM...'
BEGIN TRY
    CREATE TABLE #stg_lnk_eli (
        LNK_ID          NVARCHAR(64),
        SRC             NVARCHAR(255),
        LOAD_TS         NVARCHAR(50),
        EMPLOYEE_HUB_ID NVARCHAR(64),
        LINEITEM_HUB_ID NVARCHAR(64),
        EMPLOYEE_AGG    NVARCHAR(50),
        LINEITEM_AGG    NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_eli FROM ''' + @CsvPath + N'\lnk_employee_lineitem.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_EMPLOYEE_LINEITEM]
        (LNK_ID, SRC, LOAD_TS, EMPLOYEE_HUB_ID, LINEITEM_HUB_ID, EMPLOYEE_AGG, LINEITEM_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),EMPLOYEE_HUB_ID,2), CONVERT(BINARY(32),LINEITEM_HUB_ID,2),
               CAST(EMPLOYEE_AGG AS INT), CAST(LINEITEM_AGG AS INT)
        FROM #stg_lnk_eli';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_eli;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_eli') IS NOT NULL DROP TABLE #stg_lnk_eli;
    RETURN;
END CATCH

-- === LNK_DISCOUNT_LINEITEM ===
PRINT 'Loading LNK_DISCOUNT_LINEITEM...'
BEGIN TRY
    CREATE TABLE #stg_lnk_dli (
        LNK_ID          NVARCHAR(64),
        SRC             NVARCHAR(255),
        LOAD_TS         NVARCHAR(50),
        DISCOUNT_HUB_ID NVARCHAR(64),
        LINEITEM_HUB_ID NVARCHAR(64),
        DISCOUNT_AGG    NVARCHAR(50),
        LINEITEM_AGG    NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_dli FROM ''' + @CsvPath + N'\lnk_discount_lineitem.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_DISCOUNT_LINEITEM]
        (LNK_ID, SRC, LOAD_TS, DISCOUNT_HUB_ID, LINEITEM_HUB_ID, DISCOUNT_AGG, LINEITEM_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),DISCOUNT_HUB_ID,2), CONVERT(BINARY(32),LINEITEM_HUB_ID,2),
               CAST(DISCOUNT_AGG AS INT), CAST(LINEITEM_AGG AS INT)
        FROM #stg_lnk_dli';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_dli;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_dli') IS NOT NULL DROP TABLE #stg_lnk_dli;
    RETURN;
END CATCH

-- === LNK_INVITEM_STOCKEVENT ===
PRINT 'Loading LNK_INVITEM_STOCKEVENT...'
BEGIN TRY
    CREATE TABLE #stg_lnk_ise (
        LNK_ID             NVARCHAR(64),
        SRC                NVARCHAR(255),
        LOAD_TS            NVARCHAR(50),
        INVITEM_HUB_ID     NVARCHAR(64),
        STOCKEVENT_HUB_ID  NVARCHAR(64),
        INVITEM_AGG        NVARCHAR(50),
        STOCKEVENT_AGG     NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_ise FROM ''' + @CsvPath + N'\lnk_invitem_stockevent.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_INVITEM_STOCKEVENT]
        (LNK_ID, SRC, LOAD_TS, INVITEM_HUB_ID, STOCKEVENT_HUB_ID, INVITEM_AGG, STOCKEVENT_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),INVITEM_HUB_ID,2), CONVERT(BINARY(32),STOCKEVENT_HUB_ID,2),
               CAST(INVITEM_AGG AS INT), CAST(STOCKEVENT_AGG AS INT)
        FROM #stg_lnk_ise';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_ise;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_ise') IS NOT NULL DROP TABLE #stg_lnk_ise;
    RETURN;
END CATCH

-- === LNK_LOCATION_STOCKEVENT ===
PRINT 'Loading LNK_LOCATION_STOCKEVENT...'
BEGIN TRY
    CREATE TABLE #stg_lnk_lse (
        LNK_ID            NVARCHAR(64),
        SRC               NVARCHAR(255),
        LOAD_TS           NVARCHAR(50),
        LOCATION_HUB_ID   NVARCHAR(64),
        STOCKEVENT_HUB_ID NVARCHAR(64),
        LOCATION_AGG      NVARCHAR(50),
        STOCKEVENT_AGG    NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_lse FROM ''' + @CsvPath + N'\lnk_location_stockevent.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_LOCATION_STOCKEVENT]
        (LNK_ID, SRC, LOAD_TS, LOCATION_HUB_ID, STOCKEVENT_HUB_ID, LOCATION_AGG, STOCKEVENT_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),LOCATION_HUB_ID,2), CONVERT(BINARY(32),STOCKEVENT_HUB_ID,2),
               CAST(LOCATION_AGG AS INT), CAST(STOCKEVENT_AGG AS INT)
        FROM #stg_lnk_lse';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_lse;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_lse') IS NOT NULL DROP TABLE #stg_lnk_lse;
    RETURN;
END CATCH

-- === LNK_INVITEM_INVREPORT ===
PRINT 'Loading LNK_INVITEM_INVREPORT...'
BEGIN TRY
    CREATE TABLE #stg_lnk_iir (
        LNK_ID           NVARCHAR(64),
        SRC              NVARCHAR(255),
        LOAD_TS          NVARCHAR(50),
        INVITEM_HUB_ID   NVARCHAR(64),
        INVREPORT_HUB_ID NVARCHAR(64),
        INVITEM_AGG      NVARCHAR(50),
        INVREPORT_AGG    NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_iir FROM ''' + @CsvPath + N'\lnk_invitem_invreport.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_INVITEM_INVREPORT]
        (LNK_ID, SRC, LOAD_TS, INVITEM_HUB_ID, INVREPORT_HUB_ID, INVITEM_AGG, INVREPORT_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),INVITEM_HUB_ID,2), CONVERT(BINARY(32),INVREPORT_HUB_ID,2),
               CAST(INVITEM_AGG AS INT), CAST(INVREPORT_AGG AS INT)
        FROM #stg_lnk_iir';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_iir;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_iir') IS NOT NULL DROP TABLE #stg_lnk_iir;
    RETURN;
END CATCH

-- === LNK_INVREPORT_LOCATION ===
PRINT 'Loading LNK_INVREPORT_LOCATION...'
BEGIN TRY
    CREATE TABLE #stg_lnk_irl (
        LNK_ID           NVARCHAR(64),
        SRC              NVARCHAR(255),
        LOAD_TS          NVARCHAR(50),
        INVREPORT_HUB_ID NVARCHAR(64),
        LOCATION_HUB_ID  NVARCHAR(64),
        INVREPORT_AGG    NVARCHAR(50),
        LOCATION_AGG     NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_irl FROM ''' + @CsvPath + N'\lnk_invreport_location.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_INVREPORT_LOCATION]
        (LNK_ID, SRC, LOAD_TS, INVREPORT_HUB_ID, LOCATION_HUB_ID, INVREPORT_AGG, LOCATION_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),INVREPORT_HUB_ID,2), CONVERT(BINARY(32),LOCATION_HUB_ID,2),
               CAST(INVREPORT_AGG AS INT), CAST(LOCATION_AGG AS INT)
        FROM #stg_lnk_irl';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_irl;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_irl') IS NOT NULL DROP TABLE #stg_lnk_irl;
    RETURN;
END CATCH

-- === LNK_LINEITEM_LINEITEM (self-ref) ===
PRINT 'Loading LNK_LINEITEM_LINEITEM...'
BEGIN TRY
    CREATE TABLE #stg_lnk_lili (
        LNK_ID        NVARCHAR(64),
        SRC           NVARCHAR(255),
        LOAD_TS       NVARCHAR(50),
        PARENT_HUB_ID NVARCHAR(64),
        CHILD_HUB_ID  NVARCHAR(64),
        PARENT_AGG    NVARCHAR(50),
        CHILD_AGG     NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_lili FROM ''' + @CsvPath + N'\lnk_lineitem_lineitem.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_LINEITEM_LINEITEM]
        (LNK_ID, SRC, LOAD_TS, PARENT_HUB_ID, CHILD_HUB_ID, PARENT_AGG, CHILD_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),PARENT_HUB_ID,2), CONVERT(BINARY(32),CHILD_HUB_ID,2),
               CAST(PARENT_AGG AS INT), CAST(CHILD_AGG AS INT)
        FROM #stg_lnk_lili';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_lili;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_lili') IS NOT NULL DROP TABLE #stg_lnk_lili;
    RETURN;
END CATCH

-- === LNK_INVITEM_INVITEM (self-ref) ===
PRINT 'Loading LNK_INVITEM_INVITEM...'
BEGIN TRY
    CREATE TABLE #stg_lnk_invi (
        LNK_ID        NVARCHAR(64),
        SRC           NVARCHAR(255),
        LOAD_TS       NVARCHAR(50),
        PARENT_HUB_ID NVARCHAR(64),
        CHILD_HUB_ID  NVARCHAR(64),
        PARENT_AGG    NVARCHAR(50),
        CHILD_AGG     NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_lnk_invi FROM ''' + @CsvPath + N'\lnk_invitem_invitem.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_INVITEM_INVITEM]
        (LNK_ID, SRC, LOAD_TS, PARENT_HUB_ID, CHILD_HUB_ID, PARENT_AGG, CHILD_AGG)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),PARENT_HUB_ID,2), CONVERT(BINARY(32),CHILD_HUB_ID,2),
               CAST(PARENT_AGG AS INT), CAST(CHILD_AGG AS INT)
        FROM #stg_lnk_invi';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_invi;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_invi') IS NOT NULL DROP TABLE #stg_lnk_invi;
    RETURN;
END CATCH

-- === LNK_INVITEM_OCCASION_PRODUCT (multi-way) ===
PRINT 'Loading LNK_INVITEM_OCCASION_PRODUCT...'
BEGIN TRY
    CREATE TABLE #stg_lnk_iop (
        LNK_ID          NVARCHAR(64),
        SRC             NVARCHAR(255),
        LOAD_TS         NVARCHAR(50),
        INVITEM_HUB_ID  NVARCHAR(64),
        OCCASION_HUB_ID NVARCHAR(64),
        PRODUCT_HUB_ID  NVARCHAR(64)
    );
    SET @sql = N'BULK INSERT #stg_lnk_iop FROM ''' + @CsvPath + N'\lnk_invitem_occasion_product.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_INVITEM_OCCASION_PRODUCT]
        (LNK_ID, SRC, LOAD_TS, INVITEM_HUB_ID, OCCASION_HUB_ID, PRODUCT_HUB_ID)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),INVITEM_HUB_ID,2),
               CONVERT(BINARY(32),OCCASION_HUB_ID,2),
               CONVERT(BINARY(32),PRODUCT_HUB_ID,2)
        FROM #stg_lnk_iop';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_iop;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_iop') IS NOT NULL DROP TABLE #stg_lnk_iop;
    RETURN;
END CATCH

-- === LNK_LOCATION_OCCASION_PRODUCT (multi-way) ===
PRINT 'Loading LNK_LOCATION_OCCASION_PRODUCT...'
BEGIN TRY
    CREATE TABLE #stg_lnk_lop (
        LNK_ID          NVARCHAR(64),
        SRC             NVARCHAR(255),
        LOAD_TS         NVARCHAR(50),
        LOCATION_HUB_ID NVARCHAR(64),
        OCCASION_HUB_ID NVARCHAR(64),
        PRODUCT_HUB_ID  NVARCHAR(64)
    );
    SET @sql = N'BULK INSERT #stg_lnk_lop FROM ''' + @CsvPath + N'\lnk_location_occasion_product.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_LOCATION_OCCASION_PRODUCT]
        (LNK_ID, SRC, LOAD_TS, LOCATION_HUB_ID, OCCASION_HUB_ID, PRODUCT_HUB_ID)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),LOCATION_HUB_ID,2),
               CONVERT(BINARY(32),OCCASION_HUB_ID,2),
               CONVERT(BINARY(32),PRODUCT_HUB_ID,2)
        FROM #stg_lnk_lop';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_lop;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_lop') IS NOT NULL DROP TABLE #stg_lnk_lop;
    RETURN;
END CATCH

-- === LNK_INVITEM_LOCATION_OCCASION_PRODUCT (multi-way) ===
PRINT 'Loading LNK_INVITEM_LOCATION_OCCASION_PRODUCT...'
BEGIN TRY
    CREATE TABLE #stg_lnk_ilop (
        LNK_ID          NVARCHAR(64),
        SRC             NVARCHAR(255),
        LOAD_TS         NVARCHAR(50),
        INVITEM_HUB_ID  NVARCHAR(64),
        LOCATION_HUB_ID NVARCHAR(64),
        OCCASION_HUB_ID NVARCHAR(64),
        PRODUCT_HUB_ID  NVARCHAR(64)
    );
    SET @sql = N'BULK INSERT #stg_lnk_ilop FROM ''' + @CsvPath + N'\lnk_invitem_location_occasion_product.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[LNK_INVITEM_LOCATION_OCCASION_PRODUCT]
        (LNK_ID, SRC, LOAD_TS, INVITEM_HUB_ID, LOCATION_HUB_ID, OCCASION_HUB_ID, PRODUCT_HUB_ID)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CONVERT(BINARY(32),INVITEM_HUB_ID,2),
               CONVERT(BINARY(32),LOCATION_HUB_ID,2),
               CONVERT(BINARY(32),OCCASION_HUB_ID,2),
               CONVERT(BINARY(32),PRODUCT_HUB_ID,2)
        FROM #stg_lnk_ilop';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_lnk_ilop;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_lnk_ilop') IS NOT NULL DROP TABLE #stg_lnk_ilop;
    RETURN;
END CATCH

GO

-- =========================================
-- Phase 4: Link Satellites
-- =========================================
PRINT ''
PRINT '--- Phase 4: Link Satellites ---'

DECLARE @CsvPath     NVARCHAR(500) = N'C:\threerocks_data\XMS BI\Release\ClaudeDevelopment\demo-data\output';
DECLARE @DatabaseName NVARCHAR(255) = N'20260316_XMS_{GUID}';
DECLARE @sql         NVARCHAR(MAX);

-- === SAT_LNK_LINEITEM_LINEITEM ===
PRINT 'Loading SAT_LNK_LINEITEM_LINEITEM...'
BEGIN TRY
    CREATE TABLE #stg_slnk_lili (
        LNK_ID  NVARCHAR(64),
        SRC     NVARCHAR(255),
        LOAD_TS NVARCHAR(50),
        LABEL   NVARCHAR(255),
        VALUE   NVARCHAR(255),
        INFO    NVARCHAR(255)
    );
    SET @sql = N'BULK INSERT #stg_slnk_lili FROM ''' + @CsvPath + N'\sat_lnk_lineitem_lineitem.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_LNK_LINEITEM_LINEITEM]
        (LNK_ID, SRC, LOAD_TS, LABEL, VALUE, INFO)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               LABEL, VALUE, INFO
        FROM #stg_slnk_lili';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_slnk_lili;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_slnk_lili') IS NOT NULL DROP TABLE #stg_slnk_lili;
    RETURN;
END CATCH

-- === SAT_LNK_INVITEM_INVITEM ===
PRINT 'Loading SAT_LNK_INVITEM_INVITEM...'
BEGIN TRY
    CREATE TABLE #stg_slnk_invi (
        LNK_ID    NVARCHAR(64),
        SRC       NVARCHAR(255),
        LOAD_TS   NVARCHAR(50),
        UOM       NVARCHAR(50),
        UOM_VALUE NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_slnk_invi FROM ''' + @CsvPath + N'\sat_lnk_invitem_invitem.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_LNK_INVITEM_INVITEM]
        (LNK_ID, SRC, LOAD_TS, UOM, UOM_VALUE)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               UOM, CAST(UOM_VALUE AS DECIMAL(18,6))
        FROM #stg_slnk_invi';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_slnk_invi;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_slnk_invi') IS NOT NULL DROP TABLE #stg_slnk_invi;
    RETURN;
END CATCH

-- === SAT_LNK_INVITEM_OCCASION_PRODUCT ===
PRINT 'Loading SAT_LNK_INVITEM_OCCASION_PRODUCT...'
BEGIN TRY
    CREATE TABLE #stg_slnk_iop (
        LNK_ID    NVARCHAR(64),
        SRC       NVARCHAR(255),
        LOAD_TS   NVARCHAR(50),
        UOM       NVARCHAR(50),
        UOM_VALUE NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_slnk_iop FROM ''' + @CsvPath + N'\sat_lnk_invitem_occasion_product.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_LNK_INVITEM_OCCASION_PRODUCT]
        (LNK_ID, SRC, LOAD_TS, UOM, UOM_VALUE)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               UOM, CAST(UOM_VALUE AS DECIMAL(18,6))
        FROM #stg_slnk_iop';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_slnk_iop;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_slnk_iop') IS NOT NULL DROP TABLE #stg_slnk_iop;
    RETURN;
END CATCH

-- === SAT_LNK_LOCATION_OCCASION_PRODUCT ===
PRINT 'Loading SAT_LNK_LOCATION_OCCASION_PRODUCT...'
BEGIN TRY
    CREATE TABLE #stg_slnk_lop (
        LNK_ID     NVARCHAR(64),
        SRC        NVARCHAR(255),
        LOAD_TS    NVARCHAR(50),
        NET_PRICE  NVARCHAR(50),
        NET_COST   NVARCHAR(50),
        PRODUCT_ID NVARCHAR(255)
    );
    SET @sql = N'BULK INSERT #stg_slnk_lop FROM ''' + @CsvPath + N'\sat_lnk_location_occasion_product.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_LNK_LOCATION_OCCASION_PRODUCT]
        (LNK_ID, SRC, LOAD_TS, NET_PRICE, NET_COST, PRODUCT_ID)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               CAST(NET_PRICE AS DECIMAL(18,4)),
               CAST(NET_COST AS DECIMAL(18,4)),
               PRODUCT_ID
        FROM #stg_slnk_lop';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_slnk_lop;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_slnk_lop') IS NOT NULL DROP TABLE #stg_slnk_lop;
    RETURN;
END CATCH

-- === SAT_LNK_INVITEM_LOCATION_OCCASION_PRODUCT ===
PRINT 'Loading SAT_LNK_INVITEM_LOCATION_OCCASION_PRODUCT...'
BEGIN TRY
    CREATE TABLE #stg_slnk_ilop (
        LNK_ID    NVARCHAR(64),
        SRC       NVARCHAR(255),
        LOAD_TS   NVARCHAR(50),
        UOM       NVARCHAR(50),
        UOM_VALUE NVARCHAR(50)
    );
    SET @sql = N'BULK INSERT #stg_slnk_ilop FROM ''' + @CsvPath + N'\sat_lnk_invitem_location_occasion_product.csv'' WITH (FIRSTROW=2, FIELDTERMINATOR=''|'', ROWTERMINATOR=''\n'', CODEPAGE=''65001'', TABLOCK)';
    EXEC sp_executesql @sql;
    SET @sql = N'INSERT INTO [' + @DatabaseName + N'].[datavault].[SAT_LNK_INVITEM_LOCATION_OCCASION_PRODUCT]
        (LNK_ID, SRC, LOAD_TS, UOM, UOM_VALUE)
        SELECT CONVERT(BINARY(32),LNK_ID,2), SRC, CAST(LOAD_TS AS DATETIME2),
               UOM, CAST(UOM_VALUE AS DECIMAL(18,6))
        FROM #stg_slnk_ilop';
    EXEC sp_executesql @sql;
    PRINT '  OK: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';
    DROP TABLE #stg_slnk_ilop;
END TRY
BEGIN CATCH
    PRINT '  FAILED: ' + ERROR_MESSAGE();
    IF OBJECT_ID('tempdb..#stg_slnk_ilop') IS NOT NULL DROP TABLE #stg_slnk_ilop;
    RETURN;
END CATCH

GO

-- =========================================
-- Post-load: Presentation Build
-- =========================================

DECLARE @DatabaseName NVARCHAR(255) = N'20260316_XMS_{GUID}';

PRINT ''
PRINT '--- Post-load: Presentation Build ---'
PRINT 'Run these manually after verifying the data loaded correctly:'
PRINT ''
PRINT '  EXEC [' + @DatabaseName + '].[core].[sp_PopulateCalendar] @YearsBefore = 2, @YearsAfter = 2'
PRINT '  EXEC [' + @DatabaseName + '].[core].[sp_ProcessPresentation]'
PRINT ''
PRINT '========================================='
PRINT 'Load complete!'
PRINT '========================================='

GO
