SELECT [OrganisationIntegrationID]
      ,[OrganisationID]
      ,[IntegrationID]
      ,[ConnectionString]
      ,[APIKey]
      ,[Username]
      ,[PasswordHash]
      ,[BaseURL]
      ,[CustomSettings]
      ,[IsEnabled]
      ,[LastSyncDate]
      ,[SyncStatus]
      ,[Notes]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[ModifiedBy]
      ,[ModifiedDate]
  FROM [core].[core].[OrganisationIntegrations]
