-- ============================================
-- STAGE_DDL Parameters Export
-- Source: UAT [core].[int_growyze001].[GlobalParameters]
-- Generated: 2026-07-06 15:17:46
-- Total Records: 13
-- ============================================

-- ParameterKey=DL_DELIVERYNOTES / Category=STAGE_DDL
IF EXISTS (SELECT 1 FROM [core].[int_growyze001].[GlobalParameters] WHERE [ParameterKey] = N'DL_DELIVERYNOTES' AND [Category] = N'STAGE_DDL')
BEGIN
    UPDATE [core].[int_growyze001].[GlobalParameters]
    SET
        [ParameterValue] = N'CREATE TABLE [int_growyze001].[DL_DELIVERYNOTES](
	[id] [nvarchar](max) NULL,
	[deliveryNoteNumber] [nvarchar](max) NULL,
	[po] [nvarchar](max) NULL,
	[deliveryDate] [nvarchar](max) NULL,
	[dateOfScanning] [nvarchar](max) NULL,
	[completedDate] [nvarchar](max) NULL,
	[approvedDate] [nvarchar](max) NULL,
	[inQueryDate] [nvarchar](max) NULL,
	[rejectedDate] [nvarchar](max) NULL,
	[supplier_id] [nvarchar](max) NULL,
	[supplier_name] [nvarchar](max) NULL,
	[supplier_contactName] [nvarchar](max) NULL,
	[supplier_email] [nvarchar](max) NULL,
	[supplier_emails] [nvarchar](max) NULL,
	[extractedFile] [nvarchar](max) NULL,
	[files] [nvarchar](max) NULL,
	[globalDiscrepancies] [nvarchar](max) NULL,
	[status] [nvarchar](max) NULL,
	[message] [nvarchar](max) NULL,
	[messageQueryToSupplier] [nvarchar](max) NULL,
	[hasReceivedQtyDiscrepancies] [nvarchar](max) NULL,
	[hasDNQtyDiscrepancies] [nvarchar](max) NULL,
	[hasReceivedOrderQtyDiscrepancies] [nvarchar](max) NULL,
	[hasNoOrderedProducts] [nvarchar](max) NULL,
	[hasNoDeliveredProducts] [nvarchar](max) NULL,
	[isCreatedManuallyWithoutOrder] [nvarchar](max) NULL,
	[commentFromOrder] [nvarchar](max) NULL,
	[isInvoiced] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[products_name] [nvarchar](max) NULL,
	[products_barcode] [nvarchar](max) NULL,
	[products_code] [nvarchar](max) NULL,
	[products_size] [nvarchar](max) NULL,
	[products_measure] [nvarchar](max) NULL,
	[products_category] [nvarchar](max) NULL,
	[products_subCategory] [nvarchar](max) NULL,
	[products_unit] [nvarchar](max) NULL,
	[products_orderQty] [nvarchar](max) NULL,
	[products_orderQtyInCase] [nvarchar](max) NULL,
	[products_orderCaseSize] [nvarchar](max) NULL,
	[products_dnQty] [nvarchar](max) NULL,
	[products_receivedQty] [nvarchar](max) NULL,
	[products_receivedQtyInCase] [nvarchar](max) NULL,
	[products_price] [nvarchar](max) NULL,
	[products_comment] [nvarchar](max) NULL,
	[products_isConfirmed] [nvarchar](max) NULL,
	[products_productDiscrepancies_deltaDNQty] [nvarchar](max) NULL,
	[products_productDiscrepancies_deltaReceivedQty] [nvarchar](max) NULL,
	[products_productDiscrepancies_deltaReceivedOrderedQty] [nvarchar](max) NULL,
	[organizationsNames] [nvarchar](max) NULL,
	[products_productDiscrepancies] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);',
        [DataType] = N'STRING',
        [Description] = N'DL_DELIVERYNOTES',
        [IsActive] = 1,
        [CreatedBy] = N'dbadmin',
        [CreatedDate] = '2026-03-11 12:04:19.840',
        [ModifiedBy] = N'dbadmin',
        [ModifiedDate] = '2026-03-18 09:43:30.193',
        [Version] = 1
    WHERE [ParameterKey] = N'DL_DELIVERYNOTES' AND [Category] = N'STAGE_DDL';
END
ELSE
BEGIN
    INSERT INTO [core].[int_growyze001].[GlobalParameters] ([ParameterKey], [ParameterValue], [DataType], [Category], [Description], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Version])
    VALUES (N'DL_DELIVERYNOTES', N'CREATE TABLE [int_growyze001].[DL_DELIVERYNOTES](
	[id] [nvarchar](max) NULL,
	[deliveryNoteNumber] [nvarchar](max) NULL,
	[po] [nvarchar](max) NULL,
	[deliveryDate] [nvarchar](max) NULL,
	[dateOfScanning] [nvarchar](max) NULL,
	[completedDate] [nvarchar](max) NULL,
	[approvedDate] [nvarchar](max) NULL,
	[inQueryDate] [nvarchar](max) NULL,
	[rejectedDate] [nvarchar](max) NULL,
	[supplier_id] [nvarchar](max) NULL,
	[supplier_name] [nvarchar](max) NULL,
	[supplier_contactName] [nvarchar](max) NULL,
	[supplier_email] [nvarchar](max) NULL,
	[supplier_emails] [nvarchar](max) NULL,
	[extractedFile] [nvarchar](max) NULL,
	[files] [nvarchar](max) NULL,
	[globalDiscrepancies] [nvarchar](max) NULL,
	[status] [nvarchar](max) NULL,
	[message] [nvarchar](max) NULL,
	[messageQueryToSupplier] [nvarchar](max) NULL,
	[hasReceivedQtyDiscrepancies] [nvarchar](max) NULL,
	[hasDNQtyDiscrepancies] [nvarchar](max) NULL,
	[hasReceivedOrderQtyDiscrepancies] [nvarchar](max) NULL,
	[hasNoOrderedProducts] [nvarchar](max) NULL,
	[hasNoDeliveredProducts] [nvarchar](max) NULL,
	[isCreatedManuallyWithoutOrder] [nvarchar](max) NULL,
	[commentFromOrder] [nvarchar](max) NULL,
	[isInvoiced] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[products_name] [nvarchar](max) NULL,
	[products_barcode] [nvarchar](max) NULL,
	[products_code] [nvarchar](max) NULL,
	[products_size] [nvarchar](max) NULL,
	[products_measure] [nvarchar](max) NULL,
	[products_category] [nvarchar](max) NULL,
	[products_subCategory] [nvarchar](max) NULL,
	[products_unit] [nvarchar](max) NULL,
	[products_orderQty] [nvarchar](max) NULL,
	[products_orderQtyInCase] [nvarchar](max) NULL,
	[products_orderCaseSize] [nvarchar](max) NULL,
	[products_dnQty] [nvarchar](max) NULL,
	[products_receivedQty] [nvarchar](max) NULL,
	[products_receivedQtyInCase] [nvarchar](max) NULL,
	[products_price] [nvarchar](max) NULL,
	[products_comment] [nvarchar](max) NULL,
	[products_isConfirmed] [nvarchar](max) NULL,
	[products_productDiscrepancies_deltaDNQty] [nvarchar](max) NULL,
	[products_productDiscrepancies_deltaReceivedQty] [nvarchar](max) NULL,
	[products_productDiscrepancies_deltaReceivedOrderedQty] [nvarchar](max) NULL,
	[organizationsNames] [nvarchar](max) NULL,
	[products_productDiscrepancies] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);', N'STRING', N'STAGE_DDL', N'DL_DELIVERYNOTES', 1, N'dbadmin', '2026-03-11 12:04:19.840', N'dbadmin', '2026-03-18 09:43:30.193', 1);
END
GO
-- ParameterKey=DL_DISHES / Category=STAGE_DDL
IF EXISTS (SELECT 1 FROM [core].[int_growyze001].[GlobalParameters] WHERE [ParameterKey] = N'DL_DISHES' AND [Category] = N'STAGE_DDL')
BEGIN
    UPDATE [core].[int_growyze001].[GlobalParameters]
    SET
        [ParameterValue] = N'CREATE TABLE [int_growyze001].[DL_DISHES](
	[id] [nvarchar](max) NULL,
	[mainDishId] [nvarchar](max) NULL,
	[name] [nvarchar](max) NULL,
	[posId] [nvarchar](max) NULL,
	[barcode] [nvarchar](max) NULL,
	[method] [nvarchar](max) NULL,
	[notes] [nvarchar](max) NULL,
	[category] [nvarchar](max) NULL,
	[totalCost] [nvarchar](max) NULL,
	[totalCostPercent] [nvarchar](max) NULL,
	[totalCostPercentBasedOnSalePriceWithTax] [nvarchar](max) NULL,
	[profit] [nvarchar](max) NULL,
	[profitPercent] [nvarchar](max) NULL,
	[salePrice] [nvarchar](max) NULL,
	[targetMarginPercent] [nvarchar](max) NULL,
	[taxPercent] [nvarchar](max) NULL,
	[suggestedSalePrice] [nvarchar](max) NULL,
	[suggestedSalePriceWithTax] [nvarchar](max) NULL,
	[salePriceWithTax] [nvarchar](max) NULL,
	[calcSalePriceWithTax] [nvarchar](max) NULL,
	[profitBasedOnSalePriceWithTax] [nvarchar](max) NULL,
	[profitPercentBasedOnSalePriceWithTax] [nvarchar](max) NULL,
	[weight] [nvarchar](max) NULL,
	[files] [nvarchar](max) NULL,
	[featuredFile] [nvarchar](max) NULL,
	[folder] [nvarchar](max) NULL,
	[createdDate] [nvarchar](max) NULL,
	[updatedDate] [nvarchar](max) NULL,
	[status] [nvarchar](max) NULL,
	[waste_cost] [nvarchar](max) NULL,
	[waste_percent] [nvarchar](max) NULL,
	[hasDeletedIngredients] [nvarchar](max) NULL,
	[useSalesPriceFromLatestSales] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[sections_name] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_id] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_supplierId] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_supplierName] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_name] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_barcode] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_unit] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_category] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_subCategory] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_measure] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_size] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_price] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_isDeleted] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_ingredients] [nvarchar](max) NULL,
	[sections_elements_ingredient_usedQty] [nvarchar](max) NULL,
	[sections_elements_ingredient_measure] [nvarchar](max) NULL,
	[sections_elements_ingredient_usedQtyInProductMeasure] [nvarchar](max) NULL,
	[sections_elements_ingredient_wasteQty] [nvarchar](max) NULL,
	[sections_elements_ingredient_wasteMeasure] [nvarchar](max) NULL,
	[sections_elements_ingredient_pureQty] [nvarchar](max) NULL,
	[sections_elements_ingredient_pureMeasure] [nvarchar](max) NULL,
	[sections_elements_ingredient_cost] [nvarchar](max) NULL,
	[sections_elements_recipe] [nvarchar](max) NULL,
	[sections_elements_otherIngredient] [nvarchar](max) NULL,
	[sections_elements_type] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_allergens] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_mayContainAllergens] [nvarchar](max) NULL,
	[waste] [nvarchar](max) NULL,
	[sections_elements_ingredient] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_id] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_name] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_posId] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_category] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_totalCost] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_yield_size] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_yield_measure] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_portion_cost] [nvarchar](max) NULL,
	[sections_elements_recipe_usedQty] [nvarchar](max) NULL,
	[sections_elements_recipe_measure] [nvarchar](max) NULL,
	[sections_elements_recipe_wasteQty] [nvarchar](max) NULL,
	[sections_elements_recipe_wasteMeasure] [nvarchar](max) NULL,
	[sections_elements_recipe_pureQty] [nvarchar](max) NULL,
	[sections_elements_recipe_pureMeasure] [nvarchar](max) NULL,
	[sections_elements_recipe_cost] [nvarchar](max) NULL,
	[sections_elements_recipe_inconsistentCost] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_name] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_cost] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_usedQty] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_measure] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);',
        [DataType] = N'STRING',
        [Description] = N'DL_DISHES',
        [IsActive] = 1,
        [CreatedBy] = N'dbadmin',
        [CreatedDate] = '2026-03-11 12:06:34.876',
        [ModifiedBy] = N'dbadmin',
        [ModifiedDate] = '2026-03-18 09:43:30.240',
        [Version] = 1
    WHERE [ParameterKey] = N'DL_DISHES' AND [Category] = N'STAGE_DDL';
END
ELSE
BEGIN
    INSERT INTO [core].[int_growyze001].[GlobalParameters] ([ParameterKey], [ParameterValue], [DataType], [Category], [Description], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Version])
    VALUES (N'DL_DISHES', N'CREATE TABLE [int_growyze001].[DL_DISHES](
	[id] [nvarchar](max) NULL,
	[mainDishId] [nvarchar](max) NULL,
	[name] [nvarchar](max) NULL,
	[posId] [nvarchar](max) NULL,
	[barcode] [nvarchar](max) NULL,
	[method] [nvarchar](max) NULL,
	[notes] [nvarchar](max) NULL,
	[category] [nvarchar](max) NULL,
	[totalCost] [nvarchar](max) NULL,
	[totalCostPercent] [nvarchar](max) NULL,
	[totalCostPercentBasedOnSalePriceWithTax] [nvarchar](max) NULL,
	[profit] [nvarchar](max) NULL,
	[profitPercent] [nvarchar](max) NULL,
	[salePrice] [nvarchar](max) NULL,
	[targetMarginPercent] [nvarchar](max) NULL,
	[taxPercent] [nvarchar](max) NULL,
	[suggestedSalePrice] [nvarchar](max) NULL,
	[suggestedSalePriceWithTax] [nvarchar](max) NULL,
	[salePriceWithTax] [nvarchar](max) NULL,
	[calcSalePriceWithTax] [nvarchar](max) NULL,
	[profitBasedOnSalePriceWithTax] [nvarchar](max) NULL,
	[profitPercentBasedOnSalePriceWithTax] [nvarchar](max) NULL,
	[weight] [nvarchar](max) NULL,
	[files] [nvarchar](max) NULL,
	[featuredFile] [nvarchar](max) NULL,
	[folder] [nvarchar](max) NULL,
	[createdDate] [nvarchar](max) NULL,
	[updatedDate] [nvarchar](max) NULL,
	[status] [nvarchar](max) NULL,
	[waste_cost] [nvarchar](max) NULL,
	[waste_percent] [nvarchar](max) NULL,
	[hasDeletedIngredients] [nvarchar](max) NULL,
	[useSalesPriceFromLatestSales] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[sections_name] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_id] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_supplierId] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_supplierName] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_name] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_barcode] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_unit] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_category] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_subCategory] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_measure] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_size] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_price] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_isDeleted] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_ingredients] [nvarchar](max) NULL,
	[sections_elements_ingredient_usedQty] [nvarchar](max) NULL,
	[sections_elements_ingredient_measure] [nvarchar](max) NULL,
	[sections_elements_ingredient_usedQtyInProductMeasure] [nvarchar](max) NULL,
	[sections_elements_ingredient_wasteQty] [nvarchar](max) NULL,
	[sections_elements_ingredient_wasteMeasure] [nvarchar](max) NULL,
	[sections_elements_ingredient_pureQty] [nvarchar](max) NULL,
	[sections_elements_ingredient_pureMeasure] [nvarchar](max) NULL,
	[sections_elements_ingredient_cost] [nvarchar](max) NULL,
	[sections_elements_recipe] [nvarchar](max) NULL,
	[sections_elements_otherIngredient] [nvarchar](max) NULL,
	[sections_elements_type] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_allergens] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_mayContainAllergens] [nvarchar](max) NULL,
	[waste] [nvarchar](max) NULL,
	[sections_elements_ingredient] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_id] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_name] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_posId] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_category] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_totalCost] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_yield_size] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_yield_measure] [nvarchar](max) NULL,
	[sections_elements_recipe_recipe_portion_cost] [nvarchar](max) NULL,
	[sections_elements_recipe_usedQty] [nvarchar](max) NULL,
	[sections_elements_recipe_measure] [nvarchar](max) NULL,
	[sections_elements_recipe_wasteQty] [nvarchar](max) NULL,
	[sections_elements_recipe_wasteMeasure] [nvarchar](max) NULL,
	[sections_elements_recipe_pureQty] [nvarchar](max) NULL,
	[sections_elements_recipe_pureMeasure] [nvarchar](max) NULL,
	[sections_elements_recipe_cost] [nvarchar](max) NULL,
	[sections_elements_recipe_inconsistentCost] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_name] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_cost] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_usedQty] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_measure] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);', N'STRING', N'STAGE_DDL', N'DL_DISHES', 1, N'dbadmin', '2026-03-11 12:06:34.876', N'dbadmin', '2026-03-18 09:43:30.240', 1);
END
GO
-- ParameterKey=DL_INVOICES / Category=STAGE_DDL
IF EXISTS (SELECT 1 FROM [core].[int_growyze001].[GlobalParameters] WHERE [ParameterKey] = N'DL_INVOICES' AND [Category] = N'STAGE_DDL')
BEGIN
    UPDATE [core].[int_growyze001].[GlobalParameters]
    SET
        [ParameterValue] = N'CREATE TABLE [int_growyze001].[DL_INVOICES](
	[id] [nvarchar](max) NULL,
	[invoiceNumber] [nvarchar](max) NULL,
	[deliveryNoteNumber] [nvarchar](max) NULL,
	[deliveryNoteId] [nvarchar](max) NULL,
	[po] [nvarchar](max) NULL,
	[deliveryNotes] [nvarchar](max) NULL,
	[dateOfIssue] [nvarchar](max) NULL,
	[dateOfScanning] [nvarchar](max) NULL,
	[dueDate] [nvarchar](max) NULL,
	[approvedDate] [nvarchar](max) NULL,
	[inQueryDate] [nvarchar](max) NULL,
	[rejectedDate] [nvarchar](max) NULL,
	[supplier_id] [nvarchar](max) NULL,
	[supplier_name] [nvarchar](max) NULL,
	[supplier_contactName] [nvarchar](max) NULL,
	[supplier_email] [nvarchar](max) NULL,
	[supplier_emails] [nvarchar](max) NULL,
	[supplier_currency] [nvarchar](max) NULL,
	[extractedFile] [nvarchar](max) NULL,
	[files] [nvarchar](max) NULL,
	[xeroInvoice] [nvarchar](max) NULL,
	[sageInvoice] [nvarchar](max) NULL,
	[totalCost] [nvarchar](max) NULL,
	[grossTotalCost] [nvarchar](max) NULL,
	[totalVat] [nvarchar](max) NULL,
	[expectedTotalCost] [nvarchar](max) NULL,
	[invoicedTotalCost] [nvarchar](max) NULL,
	[deltaTotalCost] [nvarchar](max) NULL,
	[deltaInvoicedExpectedTotalCost] [nvarchar](max) NULL,
	[globalDiscrepancies] [nvarchar](max) NULL,
	[status] [nvarchar](max) NULL,
	[message] [nvarchar](max) NULL,
	[messageQueryToSupplier] [nvarchar](max) NULL,
	[expectedPo] [nvarchar](max) NULL,
	[expectedDeliveryNoteNumber] [nvarchar](max) NULL,
	[hasQtyDiscrepancies] [nvarchar](max) NULL,
	[hasProductPriceDiscrepancies] [nvarchar](max) NULL,
	[hasNoReceivedProducts] [nvarchar](max) NULL,
	[hasNoInvoicedProducts] [nvarchar](max) NULL,
	[hasNoOrderedProducts] [nvarchar](max) NULL,
	[hasTotalCostDiscrepancy] [nvarchar](max) NULL,
	[commentFromOrders] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[products_description] [nvarchar](max) NULL,
	[products_barcode] [nvarchar](max) NULL,
	[products_code] [nvarchar](max) NULL,
	[products_size] [nvarchar](max) NULL,
	[products_measure] [nvarchar](max) NULL,
	[products_category] [nvarchar](max) NULL,
	[products_subCategory] [nvarchar](max) NULL,
	[products_unit] [nvarchar](max) NULL,
	[products_orderCaseSize] [nvarchar](max) NULL,
	[products_dnReceivedQty] [nvarchar](max) NULL,
	[products_receivedQtyInCase] [nvarchar](max) NULL,
	[products_invoiceQty] [nvarchar](max) NULL,
	[products_invoiceQtyInCase] [nvarchar](max) NULL,
	[products_invoicePrice] [nvarchar](max) NULL,
	[products_orderPrice] [nvarchar](max) NULL,
	[products_expectedTotalCost] [nvarchar](max) NULL,
	[products_invoicedTotalCost] [nvarchar](max) NULL,
	[products_comment] [nvarchar](max) NULL,
	[products_isConfirmed] [nvarchar](max) NULL,
	[products_isAcceptedPrice] [nvarchar](max) NULL,
	[products_isDuplicated] [nvarchar](max) NULL,
	[products_productDiscrepancies] [nvarchar](max) NULL,
	[products_xero] [nvarchar](max) NULL,
	[organizationsNames] [nvarchar](max) NULL,
	[sageInvoice_sageSupplier_id] [nvarchar](max) NULL,
	[sageInvoice_sageSupplier_name] [nvarchar](max) NULL,
	[sageInvoice_sageSupplier_email] [nvarchar](max) NULL,
	[sageInvoice_sageSupplier_displayedAs] [nvarchar](max) NULL,
	[sageInvoice_invoiceNumber] [nvarchar](max) NULL,
	[sageInvoice_invoiceDate] [nvarchar](max) NULL,
	[sageInvoice_dueDate] [nvarchar](max) NULL,
	[sageInvoice_netCost] [nvarchar](max) NULL,
	[sageInvoice_grossTotalCost] [nvarchar](max) NULL,
	[sageInvoice_totalVat] [nvarchar](max) NULL,
	[deliveryNotes_deliveryNoteId] [nvarchar](max) NULL,
	[deliveryNotes_deliveryNoteNumber] [nvarchar](max) NULL,
	[deliveryNotes_po] [nvarchar](max) NULL,
	[products_productDiscrepancies_deltaQty] [nvarchar](max) NULL,
	[products_productDiscrepancies_deltaPrice] [nvarchar](max) NULL,
	[products_productDiscrepancies_deltaInvoicedExpectedTotalCost] [nvarchar](max) NULL,
	[products_productDiscrepancies_notOrdered] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_id] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_name] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_code] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_type_id] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_type_displayedAs] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_taxRate_id] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_taxRate_name] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_taxRate_percentage] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_taxRate_displayedAs] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_displayedAs] [nvarchar](max) NULL,
	[sageInvoice_lineItems_description] [nvarchar](max) NULL,
	[sageInvoice_lineItems_netCost] [nvarchar](max) NULL,
	[sageInvoice_lineItems_taxRate_id] [nvarchar](max) NULL,
	[sageInvoice_lineItems_taxRate_name] [nvarchar](max) NULL,
	[sageInvoice_lineItems_taxRate_percentage] [nvarchar](max) NULL,
	[sageInvoice_lineItems_taxRate_displayedAs] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);',
        [DataType] = N'STRING',
        [Description] = N'DL_INVOICES',
        [IsActive] = 1,
        [CreatedBy] = N'dbadmin',
        [CreatedDate] = '2026-03-11 12:06:34.920',
        [ModifiedBy] = N'dbadmin',
        [ModifiedDate] = '2026-03-18 09:43:30.343',
        [Version] = 1
    WHERE [ParameterKey] = N'DL_INVOICES' AND [Category] = N'STAGE_DDL';
END
ELSE
BEGIN
    INSERT INTO [core].[int_growyze001].[GlobalParameters] ([ParameterKey], [ParameterValue], [DataType], [Category], [Description], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Version])
    VALUES (N'DL_INVOICES', N'CREATE TABLE [int_growyze001].[DL_INVOICES](
	[id] [nvarchar](max) NULL,
	[invoiceNumber] [nvarchar](max) NULL,
	[deliveryNoteNumber] [nvarchar](max) NULL,
	[deliveryNoteId] [nvarchar](max) NULL,
	[po] [nvarchar](max) NULL,
	[deliveryNotes] [nvarchar](max) NULL,
	[dateOfIssue] [nvarchar](max) NULL,
	[dateOfScanning] [nvarchar](max) NULL,
	[dueDate] [nvarchar](max) NULL,
	[approvedDate] [nvarchar](max) NULL,
	[inQueryDate] [nvarchar](max) NULL,
	[rejectedDate] [nvarchar](max) NULL,
	[supplier_id] [nvarchar](max) NULL,
	[supplier_name] [nvarchar](max) NULL,
	[supplier_contactName] [nvarchar](max) NULL,
	[supplier_email] [nvarchar](max) NULL,
	[supplier_emails] [nvarchar](max) NULL,
	[supplier_currency] [nvarchar](max) NULL,
	[extractedFile] [nvarchar](max) NULL,
	[files] [nvarchar](max) NULL,
	[xeroInvoice] [nvarchar](max) NULL,
	[sageInvoice] [nvarchar](max) NULL,
	[totalCost] [nvarchar](max) NULL,
	[grossTotalCost] [nvarchar](max) NULL,
	[totalVat] [nvarchar](max) NULL,
	[expectedTotalCost] [nvarchar](max) NULL,
	[invoicedTotalCost] [nvarchar](max) NULL,
	[deltaTotalCost] [nvarchar](max) NULL,
	[deltaInvoicedExpectedTotalCost] [nvarchar](max) NULL,
	[globalDiscrepancies] [nvarchar](max) NULL,
	[status] [nvarchar](max) NULL,
	[message] [nvarchar](max) NULL,
	[messageQueryToSupplier] [nvarchar](max) NULL,
	[expectedPo] [nvarchar](max) NULL,
	[expectedDeliveryNoteNumber] [nvarchar](max) NULL,
	[hasQtyDiscrepancies] [nvarchar](max) NULL,
	[hasProductPriceDiscrepancies] [nvarchar](max) NULL,
	[hasNoReceivedProducts] [nvarchar](max) NULL,
	[hasNoInvoicedProducts] [nvarchar](max) NULL,
	[hasNoOrderedProducts] [nvarchar](max) NULL,
	[hasTotalCostDiscrepancy] [nvarchar](max) NULL,
	[commentFromOrders] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[products_description] [nvarchar](max) NULL,
	[products_barcode] [nvarchar](max) NULL,
	[products_code] [nvarchar](max) NULL,
	[products_size] [nvarchar](max) NULL,
	[products_measure] [nvarchar](max) NULL,
	[products_category] [nvarchar](max) NULL,
	[products_subCategory] [nvarchar](max) NULL,
	[products_unit] [nvarchar](max) NULL,
	[products_orderCaseSize] [nvarchar](max) NULL,
	[products_dnReceivedQty] [nvarchar](max) NULL,
	[products_receivedQtyInCase] [nvarchar](max) NULL,
	[products_invoiceQty] [nvarchar](max) NULL,
	[products_invoiceQtyInCase] [nvarchar](max) NULL,
	[products_invoicePrice] [nvarchar](max) NULL,
	[products_orderPrice] [nvarchar](max) NULL,
	[products_expectedTotalCost] [nvarchar](max) NULL,
	[products_invoicedTotalCost] [nvarchar](max) NULL,
	[products_comment] [nvarchar](max) NULL,
	[products_isConfirmed] [nvarchar](max) NULL,
	[products_isAcceptedPrice] [nvarchar](max) NULL,
	[products_isDuplicated] [nvarchar](max) NULL,
	[products_productDiscrepancies] [nvarchar](max) NULL,
	[products_xero] [nvarchar](max) NULL,
	[organizationsNames] [nvarchar](max) NULL,
	[sageInvoice_sageSupplier_id] [nvarchar](max) NULL,
	[sageInvoice_sageSupplier_name] [nvarchar](max) NULL,
	[sageInvoice_sageSupplier_email] [nvarchar](max) NULL,
	[sageInvoice_sageSupplier_displayedAs] [nvarchar](max) NULL,
	[sageInvoice_invoiceNumber] [nvarchar](max) NULL,
	[sageInvoice_invoiceDate] [nvarchar](max) NULL,
	[sageInvoice_dueDate] [nvarchar](max) NULL,
	[sageInvoice_netCost] [nvarchar](max) NULL,
	[sageInvoice_grossTotalCost] [nvarchar](max) NULL,
	[sageInvoice_totalVat] [nvarchar](max) NULL,
	[deliveryNotes_deliveryNoteId] [nvarchar](max) NULL,
	[deliveryNotes_deliveryNoteNumber] [nvarchar](max) NULL,
	[deliveryNotes_po] [nvarchar](max) NULL,
	[products_productDiscrepancies_deltaQty] [nvarchar](max) NULL,
	[products_productDiscrepancies_deltaPrice] [nvarchar](max) NULL,
	[products_productDiscrepancies_deltaInvoicedExpectedTotalCost] [nvarchar](max) NULL,
	[products_productDiscrepancies_notOrdered] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_id] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_name] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_code] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_type_id] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_type_displayedAs] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_taxRate_id] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_taxRate_name] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_taxRate_percentage] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_taxRate_displayedAs] [nvarchar](max) NULL,
	[sageInvoice_lineItems_account_displayedAs] [nvarchar](max) NULL,
	[sageInvoice_lineItems_description] [nvarchar](max) NULL,
	[sageInvoice_lineItems_netCost] [nvarchar](max) NULL,
	[sageInvoice_lineItems_taxRate_id] [nvarchar](max) NULL,
	[sageInvoice_lineItems_taxRate_name] [nvarchar](max) NULL,
	[sageInvoice_lineItems_taxRate_percentage] [nvarchar](max) NULL,
	[sageInvoice_lineItems_taxRate_displayedAs] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);', N'STRING', N'STAGE_DDL', N'DL_INVOICES', 1, N'dbadmin', '2026-03-11 12:06:34.920', N'dbadmin', '2026-03-18 09:43:30.343', 1);
END
GO
-- ParameterKey=DL_ORDERS / Category=STAGE_DDL
IF EXISTS (SELECT 1 FROM [core].[int_growyze001].[GlobalParameters] WHERE [ParameterKey] = N'DL_ORDERS' AND [Category] = N'STAGE_DDL')
BEGIN
    UPDATE [core].[int_growyze001].[GlobalParameters]
    SET
        [ParameterValue] = N'CREATE TABLE [int_growyze001].[DL_ORDERS](
	[id] [nvarchar](max) NULL,
	[po] [nvarchar](max) NULL,
	[status] [nvarchar](max) NULL,
	[supplier_id] [nvarchar](max) NULL,
	[supplier_accountNumber] [nvarchar](max) NULL,
	[supplier_name] [nvarchar](max) NULL,
	[supplier_contactName] [nvarchar](max) NULL,
	[supplier_email] [nvarchar](max) NULL,
	[supplier_currency] [nvarchar](max) NULL,
	[supplier_internalSupplier] [nvarchar](max) NULL,
	[isSentToSupplier] [nvarchar](max) NULL,
	[skippedSendingToSupplier] [nvarchar](max) NULL,
	[deliveryAddress_addressLine1] [nvarchar](max) NULL,
	[deliveryAddress_addressLine2] [nvarchar](max) NULL,
	[deliveryAddress_city] [nvarchar](max) NULL,
	[deliveryAddress_postCode] [nvarchar](max) NULL,
	[deliveryAddress_country] [nvarchar](max) NULL,
	[notes] [nvarchar](max) NULL,
	[comments] [nvarchar](max) NULL,
	[totalCost] [nvarchar](max) NULL,
	[placedDate] [nvarchar](max) NULL,
	[createdDate] [nvarchar](max) NULL,
	[completedDate] [nvarchar](max) NULL,
	[canceledDate] [nvarchar](max) NULL,
	[expectedDeliveryDate] [nvarchar](max) NULL,
	[approvedBy] [nvarchar](max) NULL,
	[extractedFile] [nvarchar](max) NULL,
	[isDelivered] [nvarchar](max) NULL,
	[approvers] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[items_productId] [nvarchar](max) NULL,
	[items_name] [nvarchar](max) NULL,
	[items_barcode] [nvarchar](max) NULL,
	[items_code] [nvarchar](max) NULL,
	[items_category] [nvarchar](max) NULL,
	[items_subCategory] [nvarchar](max) NULL,
	[items_unit] [nvarchar](max) NULL,
	[items_size] [nvarchar](max) NULL,
	[items_measure] [nvarchar](max) NULL,
	[items_price] [nvarchar](max) NULL,
	[items_estimatedCost] [nvarchar](max) NULL,
	[items_quantity] [nvarchar](max) NULL,
	[items_orderInCase] [nvarchar](max) NULL,
	[items_productCase] [nvarchar](max) NULL,
	[supplier_emails] [nvarchar](max) NULL,
	[organizationsNames] [nvarchar](max) NULL,
	[items_productCase_code] [nvarchar](max) NULL,
	[items_productCase_size] [nvarchar](max) NULL,
	[items_productCase_price] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);',
        [DataType] = N'STRING',
        [Description] = N'DL_ORDERS',
        [IsActive] = 1,
        [CreatedBy] = N'dbadmin',
        [CreatedDate] = '2026-03-11 12:04:20.083',
        [ModifiedBy] = N'dbadmin',
        [ModifiedDate] = '2026-03-18 09:43:30.383',
        [Version] = 1
    WHERE [ParameterKey] = N'DL_ORDERS' AND [Category] = N'STAGE_DDL';
END
ELSE
BEGIN
    INSERT INTO [core].[int_growyze001].[GlobalParameters] ([ParameterKey], [ParameterValue], [DataType], [Category], [Description], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Version])
    VALUES (N'DL_ORDERS', N'CREATE TABLE [int_growyze001].[DL_ORDERS](
	[id] [nvarchar](max) NULL,
	[po] [nvarchar](max) NULL,
	[status] [nvarchar](max) NULL,
	[supplier_id] [nvarchar](max) NULL,
	[supplier_accountNumber] [nvarchar](max) NULL,
	[supplier_name] [nvarchar](max) NULL,
	[supplier_contactName] [nvarchar](max) NULL,
	[supplier_email] [nvarchar](max) NULL,
	[supplier_currency] [nvarchar](max) NULL,
	[supplier_internalSupplier] [nvarchar](max) NULL,
	[isSentToSupplier] [nvarchar](max) NULL,
	[skippedSendingToSupplier] [nvarchar](max) NULL,
	[deliveryAddress_addressLine1] [nvarchar](max) NULL,
	[deliveryAddress_addressLine2] [nvarchar](max) NULL,
	[deliveryAddress_city] [nvarchar](max) NULL,
	[deliveryAddress_postCode] [nvarchar](max) NULL,
	[deliveryAddress_country] [nvarchar](max) NULL,
	[notes] [nvarchar](max) NULL,
	[comments] [nvarchar](max) NULL,
	[totalCost] [nvarchar](max) NULL,
	[placedDate] [nvarchar](max) NULL,
	[createdDate] [nvarchar](max) NULL,
	[completedDate] [nvarchar](max) NULL,
	[canceledDate] [nvarchar](max) NULL,
	[expectedDeliveryDate] [nvarchar](max) NULL,
	[approvedBy] [nvarchar](max) NULL,
	[extractedFile] [nvarchar](max) NULL,
	[isDelivered] [nvarchar](max) NULL,
	[approvers] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[items_productId] [nvarchar](max) NULL,
	[items_name] [nvarchar](max) NULL,
	[items_barcode] [nvarchar](max) NULL,
	[items_code] [nvarchar](max) NULL,
	[items_category] [nvarchar](max) NULL,
	[items_subCategory] [nvarchar](max) NULL,
	[items_unit] [nvarchar](max) NULL,
	[items_size] [nvarchar](max) NULL,
	[items_measure] [nvarchar](max) NULL,
	[items_price] [nvarchar](max) NULL,
	[items_estimatedCost] [nvarchar](max) NULL,
	[items_quantity] [nvarchar](max) NULL,
	[items_orderInCase] [nvarchar](max) NULL,
	[items_productCase] [nvarchar](max) NULL,
	[supplier_emails] [nvarchar](max) NULL,
	[organizationsNames] [nvarchar](max) NULL,
	[items_productCase_code] [nvarchar](max) NULL,
	[items_productCase_size] [nvarchar](max) NULL,
	[items_productCase_price] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);', N'STRING', N'STAGE_DDL', N'DL_ORDERS', 1, N'dbadmin', '2026-03-11 12:04:20.083', N'dbadmin', '2026-03-18 09:43:30.383', 1);
END
GO
-- ParameterKey=DL_ORGANIZATIONS / Category=STAGE_DDL
IF EXISTS (SELECT 1 FROM [core].[int_growyze001].[GlobalParameters] WHERE [ParameterKey] = N'DL_ORGANIZATIONS' AND [Category] = N'STAGE_DDL')
BEGIN
    UPDATE [core].[int_growyze001].[GlobalParameters]
    SET
        [ParameterValue] = N'CREATE TABLE [int_growyze001].[DL_ORGANIZATIONS](
	[id] [nvarchar](max) NULL,
	[logo] [nvarchar](max) NULL,
	[companyName] [nvarchar](max) NULL,
	[address_addressLine1] [nvarchar](max) NULL,
	[address_addressLine2] [nvarchar](max) NULL,
	[address_city] [nvarchar](max) NULL,
	[address_postCode] [nvarchar](max) NULL,
	[address_country] [nvarchar](max) NULL,
	[address_zoneId] [nvarchar](max) NULL,
	[deliveryAddress] [nvarchar](max) NULL,
	[businessType] [nvarchar](max) NULL,
	[contactDetails_firstName] [nvarchar](max) NULL,
	[contactDetails_lastName] [nvarchar](max) NULL,
	[contactDetails_email] [nvarchar](max) NULL,
	[contactDetails_telephone] [nvarchar](max) NULL,
	[type] [nvarchar](max) NULL,
	[mainOrgId] [nvarchar](max) NULL,
	[subOrgIds] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);',
        [DataType] = N'STRING',
        [Description] = N'DL_ORGANIZATIONS',
        [IsActive] = 1,
        [CreatedBy] = N'dbadmin',
        [CreatedDate] = '2026-03-11 12:04:20.130',
        [ModifiedBy] = N'dbadmin',
        [ModifiedDate] = '2026-03-18 09:43:30.420',
        [Version] = 1
    WHERE [ParameterKey] = N'DL_ORGANIZATIONS' AND [Category] = N'STAGE_DDL';
END
ELSE
BEGIN
    INSERT INTO [core].[int_growyze001].[GlobalParameters] ([ParameterKey], [ParameterValue], [DataType], [Category], [Description], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Version])
    VALUES (N'DL_ORGANIZATIONS', N'CREATE TABLE [int_growyze001].[DL_ORGANIZATIONS](
	[id] [nvarchar](max) NULL,
	[logo] [nvarchar](max) NULL,
	[companyName] [nvarchar](max) NULL,
	[address_addressLine1] [nvarchar](max) NULL,
	[address_addressLine2] [nvarchar](max) NULL,
	[address_city] [nvarchar](max) NULL,
	[address_postCode] [nvarchar](max) NULL,
	[address_country] [nvarchar](max) NULL,
	[address_zoneId] [nvarchar](max) NULL,
	[deliveryAddress] [nvarchar](max) NULL,
	[businessType] [nvarchar](max) NULL,
	[contactDetails_firstName] [nvarchar](max) NULL,
	[contactDetails_lastName] [nvarchar](max) NULL,
	[contactDetails_email] [nvarchar](max) NULL,
	[contactDetails_telephone] [nvarchar](max) NULL,
	[type] [nvarchar](max) NULL,
	[mainOrgId] [nvarchar](max) NULL,
	[subOrgIds] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);', N'STRING', N'STAGE_DDL', N'DL_ORGANIZATIONS', 1, N'dbadmin', '2026-03-11 12:04:20.130', N'dbadmin', '2026-03-18 09:43:30.420', 1);
END
GO
-- ParameterKey=DL_PRODUCTS / Category=STAGE_DDL
IF EXISTS (SELECT 1 FROM [core].[int_growyze001].[GlobalParameters] WHERE [ParameterKey] = N'DL_PRODUCTS' AND [Category] = N'STAGE_DDL')
BEGIN
    UPDATE [core].[int_growyze001].[GlobalParameters]
    SET
        [ParameterValue] = N'CREATE TABLE [int_growyze001].[DL_PRODUCTS](
	[id] [nvarchar](max) NULL,
	[groupId] [nvarchar](max) NULL,
	[mainProductId] [nvarchar](max) NULL,
	[supplierId] [nvarchar](max) NULL,
	[name] [nvarchar](max) NULL,
	[barcode] [nvarchar](max) NULL,
	[autoGenBarcode] [nvarchar](max) NULL,
	[posId] [nvarchar](max) NULL,
	[code] [nvarchar](max) NULL,
	[category] [nvarchar](max) NULL,
	[subCategory] [nvarchar](max) NULL,
	[unit] [nvarchar](max) NULL,
	[measure] [nvarchar](max) NULL,
	[size] [nvarchar](max) NULL,
	[price] [nvarchar](max) NULL,
	[notes] [nvarchar](max) NULL,
	[description] [nvarchar](max) NULL,
	[minQtyInStock] [nvarchar](max) NULL,
	[productCase_code] [nvarchar](max) NULL,
	[productCase_size] [nvarchar](max) NULL,
	[productCase_price] [nvarchar](max) NULL,
	[favourite] [nvarchar](max) NULL,
	[mostOrdered] [nvarchar](max) NULL,
	[preferred] [nvarchar](max) NULL,
	[allergensValidation] [nvarchar](max) NULL,
	[ingredients] [nvarchar](max) NULL,
	[orderedIn_single] [nvarchar](max) NULL,
	[orderedIn_pack] [nvarchar](max) NULL,
	[orderedIn_both] [nvarchar](max) NULL,
	[accounting] [nvarchar](max) NULL,
	[supplierName] [nvarchar](max) NULL,
	[countOfProductsInGroup] [nvarchar](max) NULL,
	[stockOnHand] [nvarchar](max) NULL,
	[stockTakeDate] [nvarchar](max) NULL,
	[avgWeeklyConsumption] [nvarchar](max) NULL,
	[awaitingDelivery] [nvarchar](max) NULL,
	[lastOrdered] [nvarchar](max) NULL,
	[lastOrderedLocation] [nvarchar](max) NULL,
	[lastCountedQty] [nvarchar](max) NULL,
	[lastCounted] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[productCase] [nvarchar](max) NULL,
	[barcodes] [nvarchar](max) NULL,
	[allergens] [nvarchar](max) NULL,
	[mayContainAllergens] [nvarchar](max) NULL,
	[orderedIn] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);',
        [DataType] = N'STRING',
        [Description] = N'DL_PRODUCTS',
        [IsActive] = 1,
        [CreatedBy] = N'dbadmin',
        [CreatedDate] = '2026-03-11 12:04:20.223',
        [ModifiedBy] = N'dbadmin',
        [ModifiedDate] = '2026-03-18 09:43:30.513',
        [Version] = 1
    WHERE [ParameterKey] = N'DL_PRODUCTS' AND [Category] = N'STAGE_DDL';
END
ELSE
BEGIN
    INSERT INTO [core].[int_growyze001].[GlobalParameters] ([ParameterKey], [ParameterValue], [DataType], [Category], [Description], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Version])
    VALUES (N'DL_PRODUCTS', N'CREATE TABLE [int_growyze001].[DL_PRODUCTS](
	[id] [nvarchar](max) NULL,
	[groupId] [nvarchar](max) NULL,
	[mainProductId] [nvarchar](max) NULL,
	[supplierId] [nvarchar](max) NULL,
	[name] [nvarchar](max) NULL,
	[barcode] [nvarchar](max) NULL,
	[autoGenBarcode] [nvarchar](max) NULL,
	[posId] [nvarchar](max) NULL,
	[code] [nvarchar](max) NULL,
	[category] [nvarchar](max) NULL,
	[subCategory] [nvarchar](max) NULL,
	[unit] [nvarchar](max) NULL,
	[measure] [nvarchar](max) NULL,
	[size] [nvarchar](max) NULL,
	[price] [nvarchar](max) NULL,
	[notes] [nvarchar](max) NULL,
	[description] [nvarchar](max) NULL,
	[minQtyInStock] [nvarchar](max) NULL,
	[productCase_code] [nvarchar](max) NULL,
	[productCase_size] [nvarchar](max) NULL,
	[productCase_price] [nvarchar](max) NULL,
	[favourite] [nvarchar](max) NULL,
	[mostOrdered] [nvarchar](max) NULL,
	[preferred] [nvarchar](max) NULL,
	[allergensValidation] [nvarchar](max) NULL,
	[ingredients] [nvarchar](max) NULL,
	[orderedIn_single] [nvarchar](max) NULL,
	[orderedIn_pack] [nvarchar](max) NULL,
	[orderedIn_both] [nvarchar](max) NULL,
	[accounting] [nvarchar](max) NULL,
	[supplierName] [nvarchar](max) NULL,
	[countOfProductsInGroup] [nvarchar](max) NULL,
	[stockOnHand] [nvarchar](max) NULL,
	[stockTakeDate] [nvarchar](max) NULL,
	[avgWeeklyConsumption] [nvarchar](max) NULL,
	[awaitingDelivery] [nvarchar](max) NULL,
	[lastOrdered] [nvarchar](max) NULL,
	[lastOrderedLocation] [nvarchar](max) NULL,
	[lastCountedQty] [nvarchar](max) NULL,
	[lastCounted] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[productCase] [nvarchar](max) NULL,
	[barcodes] [nvarchar](max) NULL,
	[allergens] [nvarchar](max) NULL,
	[mayContainAllergens] [nvarchar](max) NULL,
	[orderedIn] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);', N'STRING', N'STAGE_DDL', N'DL_PRODUCTS', 1, N'dbadmin', '2026-03-11 12:04:20.223', N'dbadmin', '2026-03-18 09:43:30.513', 1);
END
GO
-- ParameterKey=DL_RECIPES / Category=STAGE_DDL
IF EXISTS (SELECT 1 FROM [core].[int_growyze001].[GlobalParameters] WHERE [ParameterKey] = N'DL_RECIPES' AND [Category] = N'STAGE_DDL')
BEGIN
    UPDATE [core].[int_growyze001].[GlobalParameters]
    SET
        [ParameterValue] = N'CREATE TABLE [int_growyze001].[DL_RECIPES](
	[id] [nvarchar](max) NULL,
	[mainRecipeId] [nvarchar](max) NULL,
	[name] [nvarchar](max) NULL,
	[description] [nvarchar](max) NULL,
	[notes] [nvarchar](max) NULL,
	[category] [nvarchar](max) NULL,
	[posId] [nvarchar](max) NULL,
	[barcode] [nvarchar](max) NULL,
	[totalCost] [nvarchar](max) NULL,
	[totalCostPercent] [nvarchar](max) NULL,
	[totalCostPercentBasedOnSalePriceWithTax] [nvarchar](max) NULL,
	[profit] [nvarchar](max) NULL,
	[profitPercent] [nvarchar](max) NULL,
	[salePrice] [nvarchar](max) NULL,
	[targetMarginPercent] [nvarchar](max) NULL,
	[taxPercent] [nvarchar](max) NULL,
	[suggestedSalePrice] [nvarchar](max) NULL,
	[suggestedSalePriceWithTax] [nvarchar](max) NULL,
	[salePriceWithTax] [nvarchar](max) NULL,
	[calcSalePriceWithTax] [nvarchar](max) NULL,
	[profitBasedOnSalePriceWithTax] [nvarchar](max) NULL,
	[profitPercentBasedOnSalePriceWithTax] [nvarchar](max) NULL,
	[yield] [nvarchar](max) NULL,
	[otherIngredients] [nvarchar](max) NULL,
	[otherIngredientsCost] [nvarchar](max) NULL,
	[createdDate] [nvarchar](max) NULL,
	[files] [nvarchar](max) NULL,
	[featuredFile] [nvarchar](max) NULL,
	[portionCount] [nvarchar](max) NULL,
	[portion] [nvarchar](max) NULL,
	[status] [nvarchar](max) NULL,
	[folder] [nvarchar](max) NULL,
	[waste_cost] [nvarchar](max) NULL,
	[waste_percent] [nvarchar](max) NULL,
	[hasDeletedIngredients] [nvarchar](max) NULL,
	[useSalesPriceFromLatestSales] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[sections_name] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_id] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_supplierId] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_supplierName] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_name] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_barcode] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_unit] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_category] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_subCategory] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_measure] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_size] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_price] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_isDeleted] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_ingredients] [nvarchar](max) NULL,
	[sections_elements_ingredient_usedQty] [nvarchar](max) NULL,
	[sections_elements_ingredient_measure] [nvarchar](max) NULL,
	[sections_elements_ingredient_usedQtyInProductMeasure] [nvarchar](max) NULL,
	[sections_elements_ingredient_wasteQty] [nvarchar](max) NULL,
	[sections_elements_ingredient_wasteMeasure] [nvarchar](max) NULL,
	[sections_elements_ingredient_pureQty] [nvarchar](max) NULL,
	[sections_elements_ingredient_pureMeasure] [nvarchar](max) NULL,
	[sections_elements_ingredient_cost] [nvarchar](max) NULL,
	[sections_elements_recipe] [nvarchar](max) NULL,
	[sections_elements_otherIngredient] [nvarchar](max) NULL,
	[sections_elements_type] [nvarchar](max) NULL,
	[yield_size] [nvarchar](max) NULL,
	[yield_measure] [nvarchar](max) NULL,
	[portion_size] [nvarchar](max) NULL,
	[portion_measure] [nvarchar](max) NULL,
	[portion_cost] [nvarchar](max) NULL,
	[dishes_id] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_allergens] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_mayContainAllergens] [nvarchar](max) NULL,
	[sections_elements_ingredient] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_name] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_cost] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_usedQty] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_measure] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);',
        [DataType] = N'STRING',
        [Description] = N'DL_RECIPES',
        [IsActive] = 1,
        [CreatedBy] = N'dbadmin',
        [CreatedDate] = '2026-03-11 12:04:20.276',
        [ModifiedBy] = N'dbadmin',
        [ModifiedDate] = '2026-03-18 09:43:30.556',
        [Version] = 1
    WHERE [ParameterKey] = N'DL_RECIPES' AND [Category] = N'STAGE_DDL';
END
ELSE
BEGIN
    INSERT INTO [core].[int_growyze001].[GlobalParameters] ([ParameterKey], [ParameterValue], [DataType], [Category], [Description], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Version])
    VALUES (N'DL_RECIPES', N'CREATE TABLE [int_growyze001].[DL_RECIPES](
	[id] [nvarchar](max) NULL,
	[mainRecipeId] [nvarchar](max) NULL,
	[name] [nvarchar](max) NULL,
	[description] [nvarchar](max) NULL,
	[notes] [nvarchar](max) NULL,
	[category] [nvarchar](max) NULL,
	[posId] [nvarchar](max) NULL,
	[barcode] [nvarchar](max) NULL,
	[totalCost] [nvarchar](max) NULL,
	[totalCostPercent] [nvarchar](max) NULL,
	[totalCostPercentBasedOnSalePriceWithTax] [nvarchar](max) NULL,
	[profit] [nvarchar](max) NULL,
	[profitPercent] [nvarchar](max) NULL,
	[salePrice] [nvarchar](max) NULL,
	[targetMarginPercent] [nvarchar](max) NULL,
	[taxPercent] [nvarchar](max) NULL,
	[suggestedSalePrice] [nvarchar](max) NULL,
	[suggestedSalePriceWithTax] [nvarchar](max) NULL,
	[salePriceWithTax] [nvarchar](max) NULL,
	[calcSalePriceWithTax] [nvarchar](max) NULL,
	[profitBasedOnSalePriceWithTax] [nvarchar](max) NULL,
	[profitPercentBasedOnSalePriceWithTax] [nvarchar](max) NULL,
	[yield] [nvarchar](max) NULL,
	[otherIngredients] [nvarchar](max) NULL,
	[otherIngredientsCost] [nvarchar](max) NULL,
	[createdDate] [nvarchar](max) NULL,
	[files] [nvarchar](max) NULL,
	[featuredFile] [nvarchar](max) NULL,
	[portionCount] [nvarchar](max) NULL,
	[portion] [nvarchar](max) NULL,
	[status] [nvarchar](max) NULL,
	[folder] [nvarchar](max) NULL,
	[waste_cost] [nvarchar](max) NULL,
	[waste_percent] [nvarchar](max) NULL,
	[hasDeletedIngredients] [nvarchar](max) NULL,
	[useSalesPriceFromLatestSales] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[sections_name] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_id] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_supplierId] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_supplierName] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_name] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_barcode] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_unit] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_category] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_subCategory] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_measure] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_size] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_price] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_isDeleted] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_ingredients] [nvarchar](max) NULL,
	[sections_elements_ingredient_usedQty] [nvarchar](max) NULL,
	[sections_elements_ingredient_measure] [nvarchar](max) NULL,
	[sections_elements_ingredient_usedQtyInProductMeasure] [nvarchar](max) NULL,
	[sections_elements_ingredient_wasteQty] [nvarchar](max) NULL,
	[sections_elements_ingredient_wasteMeasure] [nvarchar](max) NULL,
	[sections_elements_ingredient_pureQty] [nvarchar](max) NULL,
	[sections_elements_ingredient_pureMeasure] [nvarchar](max) NULL,
	[sections_elements_ingredient_cost] [nvarchar](max) NULL,
	[sections_elements_recipe] [nvarchar](max) NULL,
	[sections_elements_otherIngredient] [nvarchar](max) NULL,
	[sections_elements_type] [nvarchar](max) NULL,
	[yield_size] [nvarchar](max) NULL,
	[yield_measure] [nvarchar](max) NULL,
	[portion_size] [nvarchar](max) NULL,
	[portion_measure] [nvarchar](max) NULL,
	[portion_cost] [nvarchar](max) NULL,
	[dishes_id] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_allergens] [nvarchar](max) NULL,
	[sections_elements_ingredient_product_mayContainAllergens] [nvarchar](max) NULL,
	[sections_elements_ingredient] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_name] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_cost] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_usedQty] [nvarchar](max) NULL,
	[sections_elements_otherIngredient_measure] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);', N'STRING', N'STAGE_DDL', N'DL_RECIPES', 1, N'dbadmin', '2026-03-11 12:04:20.276', N'dbadmin', '2026-03-18 09:43:30.556', 1);
END
GO
-- ParameterKey=DL_SALES / Category=STAGE_DDL
IF EXISTS (SELECT 1 FROM [core].[int_growyze001].[GlobalParameters] WHERE [ParameterKey] = N'DL_SALES' AND [Category] = N'STAGE_DDL')
BEGIN
    UPDATE [core].[int_growyze001].[GlobalParameters]
    SET
        [ParameterValue] = N'CREATE TABLE [int_growyze001].[DL_SALES](
	[id] [nvarchar](max) NULL,
	[name] [nvarchar](max) NULL,
	[from] [nvarchar](max) NULL,
	[to] [nvarchar](max) NULL,
	[totalSales] [nvarchar](max) NULL,
	[items] [nvarchar](max) NULL,
	[nonMatchingPosIdsCount] [nvarchar](max) NULL,
	[autoGeneratedPosIdsCount] [nvarchar](max) NULL,
	[isFromSquare] [nvarchar](max) NULL,
	[isLive] [nvarchar](max) NULL,
	[salesOrigin] [nvarchar](max) NULL,
	[createdAt] [nvarchar](max) NULL,
	[updatedAt] [nvarchar](max) NULL,
	[metadata_orderId] [nvarchar](max) NULL,
	[subSales] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);',
        [DataType] = N'STRING',
        [Description] = N'DL_SALES',
        [IsActive] = 1,
        [CreatedBy] = N'dbadmin',
        [CreatedDate] = '2026-03-11 12:04:20.316',
        [ModifiedBy] = N'dbadmin',
        [ModifiedDate] = '2026-03-18 09:43:30.593',
        [Version] = 1
    WHERE [ParameterKey] = N'DL_SALES' AND [Category] = N'STAGE_DDL';
END
ELSE
BEGIN
    INSERT INTO [core].[int_growyze001].[GlobalParameters] ([ParameterKey], [ParameterValue], [DataType], [Category], [Description], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Version])
    VALUES (N'DL_SALES', N'CREATE TABLE [int_growyze001].[DL_SALES](
	[id] [nvarchar](max) NULL,
	[name] [nvarchar](max) NULL,
	[from] [nvarchar](max) NULL,
	[to] [nvarchar](max) NULL,
	[totalSales] [nvarchar](max) NULL,
	[items] [nvarchar](max) NULL,
	[nonMatchingPosIdsCount] [nvarchar](max) NULL,
	[autoGeneratedPosIdsCount] [nvarchar](max) NULL,
	[isFromSquare] [nvarchar](max) NULL,
	[isLive] [nvarchar](max) NULL,
	[salesOrigin] [nvarchar](max) NULL,
	[createdAt] [nvarchar](max) NULL,
	[updatedAt] [nvarchar](max) NULL,
	[metadata_orderId] [nvarchar](max) NULL,
	[subSales] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);', N'STRING', N'STAGE_DDL', N'DL_SALES', 1, N'dbadmin', '2026-03-11 12:04:20.316', N'dbadmin', '2026-03-18 09:43:30.593', 1);
END
GO
-- ParameterKey=DL_SALESDETAIL / Category=STAGE_DDL
IF EXISTS (SELECT 1 FROM [core].[int_growyze001].[GlobalParameters] WHERE [ParameterKey] = N'DL_SALESDETAIL' AND [Category] = N'STAGE_DDL')
BEGIN
    UPDATE [core].[int_growyze001].[GlobalParameters]
    SET
        [ParameterValue] = N'CREATE TABLE [int_growyze001].[DL_SALESDETAIL](
	[id] [nvarchar](max) NULL,
	[name] [nvarchar](max) NULL,
	[from] [nvarchar](max) NULL,
	[to] [nvarchar](max) NULL,
	[totalSales] [nvarchar](max) NULL,
	[nonMatchingPosIdsCount] [nvarchar](max) NULL,
	[autoGeneratedPosIdsCount] [nvarchar](max) NULL,
	[isFromSquare] [nvarchar](max) NULL,
	[isLive] [nvarchar](max) NULL,
	[salesOrigin] [nvarchar](max) NULL,
	[createdAt] [nvarchar](max) NULL,
	[updatedAt] [nvarchar](max) NULL,
	[metadata_orderId] [nvarchar](max) NULL,
	[subSales] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[items_posId] [nvarchar](max) NULL,
	[items_name] [nvarchar](max) NULL,
	[items_soldQty] [nvarchar](max) NULL,
	[items_totalValue] [nvarchar](max) NULL,
	[items_nonMatchingPosId] [nvarchar](max) NULL,
	[items_autoGeneratedPosId] [nvarchar](max) NULL,
	[items_properties] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);',
        [DataType] = N'STRING',
        [Description] = N'DL_SALESDETAIL',
        [IsActive] = 1,
        [CreatedBy] = N'dbadmin',
        [CreatedDate] = '2026-03-11 12:04:20.410',
        [ModifiedBy] = N'dbadmin',
        [ModifiedDate] = '2026-03-18 09:43:30.686',
        [Version] = 1
    WHERE [ParameterKey] = N'DL_SALESDETAIL' AND [Category] = N'STAGE_DDL';
END
ELSE
BEGIN
    INSERT INTO [core].[int_growyze001].[GlobalParameters] ([ParameterKey], [ParameterValue], [DataType], [Category], [Description], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Version])
    VALUES (N'DL_SALESDETAIL', N'CREATE TABLE [int_growyze001].[DL_SALESDETAIL](
	[id] [nvarchar](max) NULL,
	[name] [nvarchar](max) NULL,
	[from] [nvarchar](max) NULL,
	[to] [nvarchar](max) NULL,
	[totalSales] [nvarchar](max) NULL,
	[nonMatchingPosIdsCount] [nvarchar](max) NULL,
	[autoGeneratedPosIdsCount] [nvarchar](max) NULL,
	[isFromSquare] [nvarchar](max) NULL,
	[isLive] [nvarchar](max) NULL,
	[salesOrigin] [nvarchar](max) NULL,
	[createdAt] [nvarchar](max) NULL,
	[updatedAt] [nvarchar](max) NULL,
	[metadata_orderId] [nvarchar](max) NULL,
	[subSales] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[items_posId] [nvarchar](max) NULL,
	[items_name] [nvarchar](max) NULL,
	[items_soldQty] [nvarchar](max) NULL,
	[items_totalValue] [nvarchar](max) NULL,
	[items_nonMatchingPosId] [nvarchar](max) NULL,
	[items_autoGeneratedPosId] [nvarchar](max) NULL,
	[items_properties] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);', N'STRING', N'STAGE_DDL', N'DL_SALESDETAIL', 1, N'dbadmin', '2026-03-11 12:04:20.410', N'dbadmin', '2026-03-18 09:43:30.686', 1);
END
GO
-- ParameterKey=DL_STOCKTAKEREPORTDETAIL / Category=STAGE_DDL
IF EXISTS (SELECT 1 FROM [core].[int_growyze001].[GlobalParameters] WHERE [ParameterKey] = N'DL_STOCKTAKEREPORTDETAIL' AND [Category] = N'STAGE_DDL')
BEGIN
    UPDATE [core].[int_growyze001].[GlobalParameters]
    SET
        [ParameterValue] = N'CREATE TABLE [int_growyze001].[DL_STOCKTAKEREPORTDETAIL](
    [id] [nvarchar](max) NULL,
    [name] [nvarchar](max) NULL,
    [note] [nvarchar](max) NULL,
    [createdAt] [nvarchar](max) NULL,
    [completedAt] [nvarchar](max) NULL,
    [status] [nvarchar](max) NULL,
    [totalAmount] [nvarchar](max) NULL,
    [totalAmountProducts] [nvarchar](max) NULL,
    [totalAmountRecipes] [nvarchar](max) NULL,
    [stockTakeTemplateId] [nvarchar](max) NULL,
    [amountByCategories] [nvarchar](max) NULL,
    [lastUpdatedAmountByCategories] [nvarchar](max) NULL,
    [subStockTakeReports_id] [nvarchar](max) NULL,
    [subStockTakeReports_name] [nvarchar](max) NULL,
    [subStockTakeReports_note] [nvarchar](max) NULL,
    [subStockTakeReports_createdAt] [nvarchar](max) NULL,
    [subStockTakeReports_completedAt] [nvarchar](max) NULL,
    [subStockTakeReports_status] [nvarchar](max) NULL,
    [subStockTakeReports_subStockTakeReports] [nvarchar](max) NULL,
    [subStockTakeReports_totalAmount] [nvarchar](max) NULL,
    [subStockTakeReports_totalAmountProducts] [nvarchar](max) NULL,
    [subStockTakeReports_totalAmountRecipes] [nvarchar](max) NULL,
    [subStockTakeReports_stockTakeTemplateId] [nvarchar](max) NULL,
    [subStockTakeReports_amountByCategories] [nvarchar](max) NULL,
    [subStockTakeReports_lastUpdatedAmountByCategories] [nvarchar](max) NULL,
    [organizations] [nvarchar](max) NULL,
    [subStockTakeReports_organizations] [nvarchar](max) NULL,
    [report_id] [nvarchar](max) NULL,
    [INT_FETCH_DATE] [datetime2](7) NULL,
    [LOADTS_UTC] [datetime2](7) NULL
);',
        [DataType] = N'STRING',
        [Description] = N'DL_STOCKTAKEREPORTDETAIL',
        [IsActive] = 1,
        [CreatedBy] = N'dbadmin',
        [CreatedDate] = '2026-03-17 17:21:41.053',
        [ModifiedBy] = N'dbadmin',
        [ModifiedDate] = '2026-03-18 09:43:30.766',
        [Version] = 1
    WHERE [ParameterKey] = N'DL_STOCKTAKEREPORTDETAIL' AND [Category] = N'STAGE_DDL';
END
ELSE
BEGIN
    INSERT INTO [core].[int_growyze001].[GlobalParameters] ([ParameterKey], [ParameterValue], [DataType], [Category], [Description], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Version])
    VALUES (N'DL_STOCKTAKEREPORTDETAIL', N'CREATE TABLE [int_growyze001].[DL_STOCKTAKEREPORTDETAIL](
    [id] [nvarchar](max) NULL,
    [name] [nvarchar](max) NULL,
    [note] [nvarchar](max) NULL,
    [createdAt] [nvarchar](max) NULL,
    [completedAt] [nvarchar](max) NULL,
    [status] [nvarchar](max) NULL,
    [totalAmount] [nvarchar](max) NULL,
    [totalAmountProducts] [nvarchar](max) NULL,
    [totalAmountRecipes] [nvarchar](max) NULL,
    [stockTakeTemplateId] [nvarchar](max) NULL,
    [amountByCategories] [nvarchar](max) NULL,
    [lastUpdatedAmountByCategories] [nvarchar](max) NULL,
    [subStockTakeReports_id] [nvarchar](max) NULL,
    [subStockTakeReports_name] [nvarchar](max) NULL,
    [subStockTakeReports_note] [nvarchar](max) NULL,
    [subStockTakeReports_createdAt] [nvarchar](max) NULL,
    [subStockTakeReports_completedAt] [nvarchar](max) NULL,
    [subStockTakeReports_status] [nvarchar](max) NULL,
    [subStockTakeReports_subStockTakeReports] [nvarchar](max) NULL,
    [subStockTakeReports_totalAmount] [nvarchar](max) NULL,
    [subStockTakeReports_totalAmountProducts] [nvarchar](max) NULL,
    [subStockTakeReports_totalAmountRecipes] [nvarchar](max) NULL,
    [subStockTakeReports_stockTakeTemplateId] [nvarchar](max) NULL,
    [subStockTakeReports_amountByCategories] [nvarchar](max) NULL,
    [subStockTakeReports_lastUpdatedAmountByCategories] [nvarchar](max) NULL,
    [organizations] [nvarchar](max) NULL,
    [subStockTakeReports_organizations] [nvarchar](max) NULL,
    [report_id] [nvarchar](max) NULL,
    [INT_FETCH_DATE] [datetime2](7) NULL,
    [LOADTS_UTC] [datetime2](7) NULL
);', N'STRING', N'STAGE_DDL', N'DL_STOCKTAKEREPORTDETAIL', 1, N'dbadmin', '2026-03-17 17:21:41.053', N'dbadmin', '2026-03-18 09:43:30.766', 1);
END
GO
-- ParameterKey=DL_STOCKTAKEREPORTPRODUCTS / Category=STAGE_DDL
IF EXISTS (SELECT 1 FROM [core].[int_growyze001].[GlobalParameters] WHERE [ParameterKey] = N'DL_STOCKTAKEREPORTPRODUCTS' AND [Category] = N'STAGE_DDL')
BEGIN
    UPDATE [core].[int_growyze001].[GlobalParameters]
    SET
        [ParameterValue] = N'CREATE TABLE [int_growyze001].[DL_STOCKTAKEREPORTPRODUCTS](
    [barcode] [nvarchar](max) NULL,
    [description] [nvarchar](max) NULL,
    [unit] [nvarchar](max) NULL,
    [size] [nvarchar](max) NULL,
    [measure] [nvarchar](max) NULL,
    [category] [nvarchar](max) NULL,
    [subCategory] [nvarchar](max) NULL,
    [quantity] [nvarchar](max) NULL,
    [price] [nvarchar](max) NULL,
    [totalAmount] [nvarchar](max) NULL,
    [highestPrice] [nvarchar](max) NULL,
    [caseSize] [nvarchar](max) NULL,
    [countedInCase] [nvarchar](max) NULL,
    [report_id] [nvarchar](max) NULL,
    [organizations] [nvarchar](max) NULL,
    [INT_FETCH_DATE] [datetime2](7) NULL,
    [LOADTS_UTC] [datetime2](7) NULL
);',
        [DataType] = N'STRING',
        [Description] = N'DL_STOCKTAKEREPORTPRODUCTS',
        [IsActive] = 1,
        [CreatedBy] = N'dbadmin',
        [CreatedDate] = '2026-03-17 17:21:41.100',
        [ModifiedBy] = N'dbadmin',
        [ModifiedDate] = '2026-03-18 09:43:30.806',
        [Version] = 1
    WHERE [ParameterKey] = N'DL_STOCKTAKEREPORTPRODUCTS' AND [Category] = N'STAGE_DDL';
END
ELSE
BEGIN
    INSERT INTO [core].[int_growyze001].[GlobalParameters] ([ParameterKey], [ParameterValue], [DataType], [Category], [Description], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Version])
    VALUES (N'DL_STOCKTAKEREPORTPRODUCTS', N'CREATE TABLE [int_growyze001].[DL_STOCKTAKEREPORTPRODUCTS](
    [barcode] [nvarchar](max) NULL,
    [description] [nvarchar](max) NULL,
    [unit] [nvarchar](max) NULL,
    [size] [nvarchar](max) NULL,
    [measure] [nvarchar](max) NULL,
    [category] [nvarchar](max) NULL,
    [subCategory] [nvarchar](max) NULL,
    [quantity] [nvarchar](max) NULL,
    [price] [nvarchar](max) NULL,
    [totalAmount] [nvarchar](max) NULL,
    [highestPrice] [nvarchar](max) NULL,
    [caseSize] [nvarchar](max) NULL,
    [countedInCase] [nvarchar](max) NULL,
    [report_id] [nvarchar](max) NULL,
    [organizations] [nvarchar](max) NULL,
    [INT_FETCH_DATE] [datetime2](7) NULL,
    [LOADTS_UTC] [datetime2](7) NULL
);', N'STRING', N'STAGE_DDL', N'DL_STOCKTAKEREPORTPRODUCTS', 1, N'dbadmin', '2026-03-17 17:21:41.100', N'dbadmin', '2026-03-18 09:43:30.806', 1);
END
GO
-- ParameterKey=DL_STOCKTAKEREPORTS / Category=STAGE_DDL
IF EXISTS (SELECT 1 FROM [core].[int_growyze001].[GlobalParameters] WHERE [ParameterKey] = N'DL_STOCKTAKEREPORTS' AND [Category] = N'STAGE_DDL')
BEGIN
    UPDATE [core].[int_growyze001].[GlobalParameters]
    SET
        [ParameterValue] = N'CREATE TABLE [int_growyze001].[DL_STOCKTAKEREPORTS](
    [stockTakeReport_id] [nvarchar](max) NULL,
    [stockTakeReport_name] [nvarchar](max) NULL,
    [stockTakeReport_note] [nvarchar](max) NULL,
    [stockTakeReport_createdAt] [nvarchar](max) NULL,
    [stockTakeReport_completedAt] [nvarchar](max) NULL,
    [stockTakeReport_status] [nvarchar](max) NULL,
    [stockTakeReport_productsCount] [nvarchar](max) NULL,
    [stockTakeReport_totalAmount] [nvarchar](max) NULL,
    [discrepancyReportId] [nvarchar](max) NULL,
    [totalDiscrepancyAmount] [nvarchar](max) NULL,
    [periodFrom] [nvarchar](max) NULL,
    [periodTo] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_id] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_name] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_note] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_createdAt] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_completedAt] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_status] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_productsCount] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_subStockTakeReports] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_totalAmount] [nvarchar](max) NULL,
    [stockTakeReport_organizations] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_organizations] [nvarchar](max) NULL,
    [INT_FETCH_DATE] [datetime2](7) NULL,
    [LOADTS_UTC] [datetime2](7) NULL
);',
        [DataType] = N'STRING',
        [Description] = N'DL_STOCKTAKEREPORTS',
        [IsActive] = 1,
        [CreatedBy] = N'dbadmin',
        [CreatedDate] = '2026-03-17 17:21:41.006',
        [ModifiedBy] = N'dbadmin',
        [ModifiedDate] = '2026-03-18 09:43:30.903',
        [Version] = 1
    WHERE [ParameterKey] = N'DL_STOCKTAKEREPORTS' AND [Category] = N'STAGE_DDL';
END
ELSE
BEGIN
    INSERT INTO [core].[int_growyze001].[GlobalParameters] ([ParameterKey], [ParameterValue], [DataType], [Category], [Description], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Version])
    VALUES (N'DL_STOCKTAKEREPORTS', N'CREATE TABLE [int_growyze001].[DL_STOCKTAKEREPORTS](
    [stockTakeReport_id] [nvarchar](max) NULL,
    [stockTakeReport_name] [nvarchar](max) NULL,
    [stockTakeReport_note] [nvarchar](max) NULL,
    [stockTakeReport_createdAt] [nvarchar](max) NULL,
    [stockTakeReport_completedAt] [nvarchar](max) NULL,
    [stockTakeReport_status] [nvarchar](max) NULL,
    [stockTakeReport_productsCount] [nvarchar](max) NULL,
    [stockTakeReport_totalAmount] [nvarchar](max) NULL,
    [discrepancyReportId] [nvarchar](max) NULL,
    [totalDiscrepancyAmount] [nvarchar](max) NULL,
    [periodFrom] [nvarchar](max) NULL,
    [periodTo] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_id] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_name] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_note] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_createdAt] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_completedAt] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_status] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_productsCount] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_subStockTakeReports] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_totalAmount] [nvarchar](max) NULL,
    [stockTakeReport_organizations] [nvarchar](max) NULL,
    [stockTakeReport_subStockTakeReports_organizations] [nvarchar](max) NULL,
    [INT_FETCH_DATE] [datetime2](7) NULL,
    [LOADTS_UTC] [datetime2](7) NULL
);', N'STRING', N'STAGE_DDL', N'DL_STOCKTAKEREPORTS', 1, N'dbadmin', '2026-03-17 17:21:41.006', N'dbadmin', '2026-03-18 09:43:30.903', 1);
END
GO
-- ParameterKey=DL_WASTES / Category=STAGE_DDL
IF EXISTS (SELECT 1 FROM [core].[int_growyze001].[GlobalParameters] WHERE [ParameterKey] = N'DL_WASTES' AND [Category] = N'STAGE_DDL')
BEGIN
    UPDATE [core].[int_growyze001].[GlobalParameters]
    SET
        [ParameterValue] = N'CREATE TABLE [int_growyze001].[DL_WASTES](
	[id] [nvarchar](max) NULL,
	[date] [nvarchar](max) NULL,
	[updatedAt] [nvarchar](max) NULL,
	[totalCost] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[products_product_id] [nvarchar](max) NULL,
	[products_product_name] [nvarchar](max) NULL,
	[products_product_barcode] [nvarchar](max) NULL,
	[products_product_category] [nvarchar](max) NULL,
	[products_product_subCategory] [nvarchar](max) NULL,
	[products_product_unit] [nvarchar](max) NULL,
	[products_product_measure] [nvarchar](max) NULL,
	[products_product_size] [nvarchar](max) NULL,
	[products_product_price] [nvarchar](max) NULL,
	[products_totalQty] [nvarchar](max) NULL,
	[products_totalCost] [nvarchar](max) NULL,
	[organizationsNames] [nvarchar](max) NULL,
	[products_wastesPerDay_id] [nvarchar](max) NULL,
	[products_wastesPerDay_fullQty] [nvarchar](max) NULL,
	[products_wastesPerDay_partialQty] [nvarchar](max) NULL,
	[products_wastesPerDay_partialQtyInProductMeasure] [nvarchar](max) NULL,
	[products_wastesPerDay_totalQty] [nvarchar](max) NULL,
	[products_wastesPerDay_wasteMeasure] [nvarchar](max) NULL,
	[products_wastesPerDay_totalCost] [nvarchar](max) NULL,
	[products_wastesPerDay_reason] [nvarchar](max) NULL,
	[products_wastesPerDay_timeOfRecord] [nvarchar](max) NULL,
	[products_wastesPerDay_reporter] [nvarchar](max) NULL,
	[products_wastesPerDay_comment] [nvarchar](max) NULL,
	[products_wastesPerDay_wasteRecipeRecordId] [nvarchar](max) NULL,
	[products_wastesPerDay_recipeName] [nvarchar](max) NULL,
	[products_wastesPerDay_wasteDishRecordId] [nvarchar](max) NULL,
	[products_wastesPerDay_dishName] [nvarchar](max) NULL,
	[products_wastesPerDay_wasteOrigin] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);',
        [DataType] = N'STRING',
        [Description] = N'DL_WASTES',
        [IsActive] = 1,
        [CreatedBy] = N'dbadmin',
        [CreatedDate] = '2026-03-11 12:04:20.503',
        [ModifiedBy] = N'dbadmin',
        [ModifiedDate] = '2026-03-18 09:43:30.946',
        [Version] = 1
    WHERE [ParameterKey] = N'DL_WASTES' AND [Category] = N'STAGE_DDL';
END
ELSE
BEGIN
    INSERT INTO [core].[int_growyze001].[GlobalParameters] ([ParameterKey], [ParameterValue], [DataType], [Category], [Description], [IsActive], [CreatedBy], [CreatedDate], [ModifiedBy], [ModifiedDate], [Version])
    VALUES (N'DL_WASTES', N'CREATE TABLE [int_growyze001].[DL_WASTES](
	[id] [nvarchar](max) NULL,
	[date] [nvarchar](max) NULL,
	[updatedAt] [nvarchar](max) NULL,
	[totalCost] [nvarchar](max) NULL,
	[organizations] [nvarchar](max) NULL,
	[products_product_id] [nvarchar](max) NULL,
	[products_product_name] [nvarchar](max) NULL,
	[products_product_barcode] [nvarchar](max) NULL,
	[products_product_category] [nvarchar](max) NULL,
	[products_product_subCategory] [nvarchar](max) NULL,
	[products_product_unit] [nvarchar](max) NULL,
	[products_product_measure] [nvarchar](max) NULL,
	[products_product_size] [nvarchar](max) NULL,
	[products_product_price] [nvarchar](max) NULL,
	[products_totalQty] [nvarchar](max) NULL,
	[products_totalCost] [nvarchar](max) NULL,
	[organizationsNames] [nvarchar](max) NULL,
	[products_wastesPerDay_id] [nvarchar](max) NULL,
	[products_wastesPerDay_fullQty] [nvarchar](max) NULL,
	[products_wastesPerDay_partialQty] [nvarchar](max) NULL,
	[products_wastesPerDay_partialQtyInProductMeasure] [nvarchar](max) NULL,
	[products_wastesPerDay_totalQty] [nvarchar](max) NULL,
	[products_wastesPerDay_wasteMeasure] [nvarchar](max) NULL,
	[products_wastesPerDay_totalCost] [nvarchar](max) NULL,
	[products_wastesPerDay_reason] [nvarchar](max) NULL,
	[products_wastesPerDay_timeOfRecord] [nvarchar](max) NULL,
	[products_wastesPerDay_reporter] [nvarchar](max) NULL,
	[products_wastesPerDay_comment] [nvarchar](max) NULL,
	[products_wastesPerDay_wasteRecipeRecordId] [nvarchar](max) NULL,
	[products_wastesPerDay_recipeName] [nvarchar](max) NULL,
	[products_wastesPerDay_wasteDishRecordId] [nvarchar](max) NULL,
	[products_wastesPerDay_dishName] [nvarchar](max) NULL,
	[products_wastesPerDay_wasteOrigin] [nvarchar](max) NULL,
	[INT_FETCH_DATE] [datetime2](7) NULL,
	[LOADTS_UTC] [datetime2](7) NULL
);', N'STRING', N'STAGE_DDL', N'DL_WASTES', 1, N'dbadmin', '2026-03-11 12:04:20.503', N'dbadmin', '2026-03-18 09:43:30.946', 1);
END
GO
